use air_common::TraceType;
use air_compile::compiled_structs::CompiledAirFn;
use airs::casm::casm_registry::{get_all_builtins, get_all_opcodes, get_sub_components};
use convert_case::{Case, Casing};
use genco::lang::rust;
use genco::quote;
use indexmap::IndexMap;
use itertools::Itertools;

use crate::utils::{AUTOGENERATED_CODE_COMMENT, is_const_size_component, is_state_component_name};

pub fn generate_claim_generator_file(
    compiled_registry: &IndexMap<String, CompiledAirFn>,
) -> rust::Tokens {
    let components_names = compiled_registry.keys().collect_vec();

    quote! {
        $(AUTOGENERATED_CODE_COMMENT.to_string())
        use std::sync::Arc;
        use cairo_air::air::PublicData;
        use cairo_air::claims::{CairoClaim, CairoInteractionClaim};
        use cairo_air::relations::CommonLookupElements;
        use indexmap::IndexSet;
        use rayon::scope;
        use stwo_cairo_adapter::builtins::BuiltinSegments;
        use stwo_cairo_adapter::memory::Memory;
        use stwo_cairo_adapter::opcodes::CasmStatesByOpcode;
        use stwo_cairo_common::builtins::*;
        use stwo_cairo_common::preprocessed_columns::preprocessed_trace::{
            PreProcessedTrace, MAX_SEQUENCE_LOG_SIZE,
        };
        use stwo_cairo_common::preprocessed_columns::simd_prelude::{BaseField, CircleEvaluation};
        pub use stwo::prover::backend::simd::SimdBackend;
        use stwo::prover::poly::BitReversedOrder;
        use crate::witness::components::*;

        #[derive(Default)]
        pub struct CairoClaimGenerator {
            pub public_data: PublicData,
            $(&components_names.iter().filter(|name| name.as_str() != "memory_id_to_small").map(|name| {
                format!("pub {name}: Option<{name}::ClaimGenerator>")
            }).collect_vec().join(", "))
        }

        impl CairoClaimGenerator {
            $(generate_fill_components(compiled_registry))

            $(generate_write_trace(compiled_registry))
        }

        #[derive(Default)]
        pub struct CairoInteractionClaimGenerator {
            $(&components_names.iter().filter(|name| name.as_str() != "memory_id_to_small").map(|name| {
                format!("pub {name}: Option<{name}::InteractionClaimGenerator>")
            }).collect_vec().join(", "))
        }

        impl CairoInteractionClaimGenerator {
            $(generate_write_interaction_trace(&components_names))
        }

       $(generate_get_sub_components())

    }
}

fn generate_fill_components(compiled_registry: &IndexMap<String, CompiledAirFn>) -> rust::Tokens {
    let mut destructure_fields = rust::Tokens::new();
    let mut spawn_bodies = rust::Tokens::new();

    for (name, compile_air_fn) in compiled_registry {
        if name == "memory_id_to_small" {
            continue;
        }

        let ref_name = format!("{name}_ref");

        destructure_fields.append(quote! {
            $(name): $(&ref_name),
        });

        let (args, builtin_init_code) = match compile_air_fn.r#type {
            TraceType::Builtin => {
                let constant_name_str = name.to_case(Case::Constant) + "_MEMORY_CELLS";
                let init_code = quote! {
                    let segment = builtin_segments.get_segment_by_name($(format!("\"{name}\""))).unwrap();
                    let segment_length = segment.stop_ptr - segment.begin_addr;
                    assert!(
                        segment_length.is_multiple_of($(&constant_name_str)),
                        $(format!("\"{} segment length is not a multiple of it's cells_per_instance\"", name))
                    );
                    let n_instances = segment_length / $(constant_name_str);
                    assert!(
                        n_instances.is_power_of_two(),
                        $(format!("\"{} instances number is not a power of two\"", name))
                    );
                };

                (quote! { n_instances.ilog2(), segment.begin_addr as u32 }, init_code)
            }
            TraceType::Opcode => (quote! { casm_states_by_opcode.$(name) }, rust::Tokens::new()),
            _ => {
                if is_const_size_component(compile_air_fn) {
                    (quote! { preprocessed_trace.clone() }, rust::Tokens::new())
                } else if is_state_component_name(name) {
                    (quote! { memory.clone() }, rust::Tokens::new())
                } else {
                    (rust::Tokens::new(), rust::Tokens::new())
                }
            }
        };

        spawn_bodies.append(quote! {
            if components.contains($(format!("&\"{name}\""))) {
                s.spawn(|_| {
                    $(builtin_init_code)
                    *$(&ref_name) = Some($(name)::ClaimGenerator::new($(args)));
                });
            }
        });
    }

    quote! {
        #[allow(clippy::redundant_closure)]
        pub fn fill_components(
            &mut self,
            components: &IndexSet<&str>,
            casm_states_by_opcode: CasmStatesByOpcode,
            builtin_segments: &BuiltinSegments,
            memory: Arc<Memory>,
            preprocessed_trace: Arc<PreProcessedTrace>,
        ){
            let Self {
                $(destructure_fields)
                public_data: _,
            } = self;

            scope(|s| {
                $(spawn_bodies)
            });
        }
    }
}

fn generate_write_trace(compiled_registry: &IndexMap<String, CompiledAirFn>) -> rust::Tokens {
    // Opcode blocks
    let mut opcodes_init_vars = rust::Tokens::new();
    let mut opcodes_spawn_blocks = rust::Tokens::new();
    let mut opcodes_extend_evals_blocks = rust::Tokens::new();

    // Non-opcode blocks
    let mut non_opcode_blocks = rust::Tokens::new();

    for (component_name, compiled_air_fn) in compiled_registry {
        let claim_var = format!("{component_name}_claim");
        let interaction_gen_var = format!("{component_name}_interaction_gen");
        let result_var = format!("{component_name}_result");

        // Collect the write trace args.
        let mut write_trace_args = rust::Tokens::new();
        for (name, _padding_type) in &compiled_air_fn.sub_components {
            write_trace_args.extend(quote! {
                self.$(name).as_ref().unwrap(),
            });
        }

        // Parallel the opcode write trace.
        if compiled_air_fn.r#type == TraceType::Opcode {
            // Init the variable before spawning the thread.
            opcodes_init_vars.append(quote! {
                let mut $(&result_var) = None;
            });

            // Add the spawn block.
            opcodes_spawn_blocks.append(quote! {
                if let Some(generator) = self.$(component_name) {
                    s.spawn(|_| {
                        $(&result_var) = Some(generator.write_trace($(write_trace_args)));
                    });
                }
            });

            // Extend trace evals after the thread is done.
            opcodes_extend_evals_blocks.append(quote! {
                let ($(&claim_var), $(&interaction_gen_var)) = $(&result_var).map(|(trace, claim, interaction_gen)| {
                    evals.extend(trace.to_evals());
                    (claim, interaction_gen)
                }).unzip();
            });
        } else {
            // Non-opcode
            if component_name == "memory_id_to_small" {
                continue;
            }

            // Special handling for memory_id_to_big.
            let non_opcode_body = if component_name == "memory_id_to_big" {
                quote! {
                    const LOG_MAX_BIG_SIZE: u32 = MAX_SEQUENCE_LOG_SIZE;
                    let (big_traces, small_trace, claim, interaction_gen) = generator.write_trace(self.range_check_9_9.as_ref().unwrap(), LOG_MAX_BIG_SIZE, opt_n_id_to_big_components);
                    for big_trace in big_traces {
                        evals.extend(big_trace);
                    }
                    evals.extend(small_trace);
                }
            } else {
                let to_evals = if component_name == "verify_bitwise_xor_12"
                    || component_name == "memory_address_to_id"
                {
                    quote! {}
                } else {
                    quote! { .to_evals() }
                };
                quote! {
                    let (trace, claim, interaction_gen) = generator.write_trace($(write_trace_args));
                    evals.extend(trace$(to_evals));
                }
            };

            non_opcode_blocks.append(quote! {
                let ($(&claim_var), $(&interaction_gen_var)) = self
                    .$(component_name)
                    .map(|generator| {
                        $(non_opcode_body)
                        (claim, interaction_gen)
                    })
                    .unzip();
            });
        }
    }

    quote! {
        pub fn write_trace(
            self,
            opt_n_id_to_big_components: Option<usize>,
        ) -> (Vec<CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>>, CairoClaim, CairoInteractionClaimGenerator) {
            let mut evals = Vec::new();
            $(opcodes_init_vars)

            scope(|s| {
                $(opcodes_spawn_blocks)
            });

            $(opcodes_extend_evals_blocks)

            $(non_opcode_blocks)

            let (memory_id_to_big_claim, memory_id_to_small_claim) = memory_id_to_big_claim.unzip();
            (
                evals,
                CairoClaim {
                    public_data: self.public_data,
                    $(&compiled_registry
                        .keys()
                        .map(|name| format!("{name}: {name}_claim,"))
                        .collect_vec()
                        .join("\n"))
                },
                CairoInteractionClaimGenerator {
                    $(&compiled_registry
                        .keys()
                        .filter(|name| name.as_str() != "memory_id_to_small")
                        .map(|name| format!("{name}: {name}_interaction_gen,"))
                        .collect_vec()
                        .join("\n"))
                },
            )
        }
    }
}

fn generate_write_interaction_trace(components_names: &Vec<&String>) -> rust::Tokens {
    let mut spawn_blocks = rust::Tokens::new();
    let mut extend_evals_blocks = rust::Tokens::new();

    for &name in components_names {
        let result_var = format!("{name}_result");

        if name == "memory_id_to_small" {
            continue;
        }

        // Spawn write interaction trace.
        spawn_blocks.append(quote! {
            if let Some(generator) = self.$(name) {
                s.spawn(|_| {
                    $(&result_var) = Some(generator.write_interaction_trace(common_lookup_elements));
                });
            }
        });
        // Extend evals for the trace after the thread is done.
        // Special handling for memory_id_to_big (tuple is (big_traces, small_trace,
        // interaction_claim)).
        if name == "memory_id_to_big" {
            extend_evals_blocks.append(quote! {
                let (memory_id_to_big_interaction_claim, memory_id_to_small_interaction_claim) = $(&result_var)
                    .map(|(big_traces, small_trace, big_interaction_claim, small_interaction_claim)| {
                        for big_trace in big_traces {
                            evals.extend(big_trace);
                        }
                        evals.extend(small_trace);
                        (big_interaction_claim, small_interaction_claim)
                    }).unzip();
            });
        } else {
            extend_evals_blocks.append(quote! {
                let $(&(name.to_string() + "_interaction_claim")) = $(&result_var)
                    .map(|(trace, interaction_claim)| {
                        evals.extend(trace);
                        interaction_claim
                    });
            });
        }
    }

    quote! {
        pub fn write_interaction_trace(
            self,
            common_lookup_elements: &CommonLookupElements,
        ) -> (Vec<CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>>, CairoInteractionClaim) {
            let mut evals = Vec::new();
            $(&components_names
                .iter()
                .filter(|name| name.as_str() != "memory_id_to_small")
                .map(|name| format!("let mut {name}_result = None;"))
                .collect_vec()
                .join("\n"))

            scope(|s| {
                $(spawn_blocks)
            });

            $(extend_evals_blocks)

            (evals,
             CairoInteractionClaim {
                $(&components_names
                    .iter()
                    .map(|name| format!("{name}: {name}_interaction_claim,"))
                    .collect_vec()
                    .join("\n"))
            })
        }
    }
}

fn generate_get_sub_components() -> rust::Tokens {
    let all_components: IndexMap<String, Vec<String>> = get_all_opcodes()
        .iter()
        .map(|opcode| (opcode.name(), get_sub_components(opcode.as_ref())))
        .chain(
            get_all_builtins()
                .iter()
                .map(|builtin| (builtin.name(), get_sub_components(builtin.as_ref()))),
        )
        .collect();

    let mut match_code = rust::Tokens::new();
    for (name, sub_components) in all_components.iter() {
        match_code.append(quote! {
            $(format!("\"{}\"", name)) => {
                vec![$(sub_components
                    .iter()
                    .map(|component| format!("\"{component}\""))
                    .join(", "))]
            }
        });
    }

    quote! {
        pub fn get_sub_components(component_name: &str) -> Vec<&'static str> {
            match component_name {
                $(match_code)
                _ => panic!("Unknown component: {component_name}"),
            }
        }
    }
}
