use air_compile::compiled_structs::CompiledAirFn;
use genco::lang::rust;
use genco::quote;
use indexmap::IndexMap;
use itertools::Itertools;

use crate::utils::{AUTOGENERATED_CODE_COMMENT, is_const_size_component};

pub fn generate_claims_rust_file(
    compiled_registry: &IndexMap<String, CompiledAirFn>,
) -> rust::Tokens {
    let components_names = compiled_registry.keys().collect_vec();
    quote! {
        $(AUTOGENERATED_CODE_COMMENT.to_string())
        use num_traits::Zero;
        use serde::{Deserialize, Serialize};
        use stwo::core::channel::{Channel, MerkleChannel};
        use stwo::core::fields::qm31::SecureField;
        use stwo_cairo_serialize::{CairoDeserialize, CairoSerialize};
        use crate::air::{
        accumulate_relation_uses, PublicData, RelationUsesDict,
        };
        use crate::components::memory_id_to_big::accumulate_relation_memory;
        use stwo::core::pcs::TreeVec;
        use crate::components::*;
        use crate::relations::CommonLookupElements;
        use super::flat_claims::FlatClaim;
        use crate::components::memory_address_to_id::MEMORY_ADDRESS_TO_ID_SPLIT;

        #[derive(Clone, Serialize, Deserialize, CairoSerialize, CairoDeserialize)]
        pub struct CairoClaim {
            pub public_data: PublicData,
            $(&components_names.iter().map(|name| {
                format!("pub {name}: Option<{name}::Claim>")
            }).collect_vec().join(", "))
        }

        $(generate_cairo_claim_impl(compiled_registry))

        #[derive(Clone, Serialize, Deserialize, CairoSerialize, CairoDeserialize)]
        pub struct CairoInteractionClaim {
            $(&components_names.iter().map(|name| {
                format!("pub {name}: Option<{name}::InteractionClaim>")
            }).collect_vec().join(", "))
        }

        $(generate_cairo_interaction_claim_impl(&components_names))

        // TODO(Stav): change it to be a sum function of the CairoInteractionClaim.
        pub fn lookup_sum(
            claim: &CairoClaim,
            common_lookup_elements: &CommonLookupElements,
            interaction_claim: &CairoInteractionClaim,
        ) -> SecureField {
            let mut sum = SecureField::zero();
            sum += claim.public_data.logup_sum(common_lookup_elements);
            $(&components_names.iter().map(|name| {
                format!("interaction_claim.{name}.as_ref().inspect(|ic| {{sum += ic.claimed_sum;}});")
            }).collect_vec().join("\n"))
            sum
        }

    }
}

pub fn generate_cairo_interaction_claim_impl(components_names: &Vec<&String>) -> rust::Tokens {
    let mut flatten_interaction_body = rust::Tokens::new();

    for &name in components_names {
        // Special handling
        if name == "memory_id_to_big" {
            flatten_interaction_body.append(quote! {
                let memory_id_to_big::InteractionClaim {
                    big_claimed_sums,
                    claimed_sum: _,
                } = self.memory_id_to_big.as_ref().unwrap();
                assert!(big_claimed_sums.len() <= MEMORY_ADDRESS_TO_ID_SPLIT);
                for claimed_sum in big_claimed_sums {
                    claimed_sums.push(*claimed_sum);
                }
            });
        } else {
            flatten_interaction_body.append(quote! {
                if let Some(c) = self.$(name) {
                    claimed_sums.push(c.claimed_sum);
                }
            });
        }
    }

    quote! {
        impl CairoInteractionClaim {
            pub fn mix_into(&self, channel: &mut impl Channel) {
                let claim = self.flatten_interaction_claim();
                channel.mix_felts(claim.as_slice());
            }

            $("/// Extracts the claimed sums from a [CairoInteractionClaim].")
            $("/// Returns a vector of all claimed sums for the logup argument, one per component.")
            $("/// The order must match the order of components as they appear in")
            $("/// [cairo_air::air::CairoComponents].")
            pub fn flatten_interaction_claim(
                &self,
            ) -> Vec<SecureField> {
                let mut claimed_sums = vec![];

                $(flatten_interaction_body)

                claimed_sums
            }
        }
    }
}

fn generate_cairo_claim_impl(compiled_registry: &IndexMap<String, CompiledAirFn>) -> rust::Tokens {
    let mut accumulate_body = rust::Tokens::new();
    let mut log_sizes_body = rust::Tokens::new();
    let mut flatten_claim_body = rust::Tokens::new();

    for (name, compiled_air_fn) in compiled_registry {
        // Add to accumulate_relation_uses() body.
        if name == "memory_id_to_big" {
            accumulate_body.append(quote! {
                accumulate_relation_memory(
                        relation_uses,
                        &self.memory_id_to_big,
                );
            });

            flatten_claim_body.append(quote! {
                let memory_id_to_big::Claim {
                    big_log_sizes,
                } = self.memory_id_to_big.as_ref().unwrap();
                assert!(big_log_sizes.len() <= MEMORY_ADDRESS_TO_ID_SPLIT);
                for log_size in big_log_sizes {
                    component_log_sizes.push(*log_size);
                    component_enable_bits.push(true);
                }
                component_enable_bits.extend(std::iter::repeat_n(false, MEMORY_ADDRESS_TO_ID_SPLIT - big_log_sizes.len()));
            });
        } else {
            if !is_const_size_component(compiled_air_fn) {
                accumulate_body.append(quote! {
                    self.$(name).as_ref().inspect(|c| {
                        accumulate_relation_uses(
                            relation_uses,
                            $(name)::RELATION_USES_PER_ROW,
                            c.log_size,
                        )
                    });
                });
            }
            let (claim_binding, log_size_expr) = if is_const_size_component(compiled_air_fn) {
                (quote! { _c }, quote! { $(name)::LOG_SIZE })
            } else {
                (quote! { c }, quote! { c.log_size })
            };

            flatten_claim_body.append(quote! {
                if let Some($(claim_binding)) = self.$(name) {
                    component_log_sizes.push($(log_size_expr));
                    component_enable_bits.push(true);
                } else {
                    component_enable_bits.push(false);
                }
            });
        }

        log_sizes_body.append(quote! {
            self.$(name).as_ref().inspect(|c| log_sizes_list.push(c.log_sizes()));
        });
    }

    quote! {
        impl CairoClaim {
            pub fn mix_into<MC: MerkleChannel>(&self, channel: &mut MC::C) {
                let flat_claim = self.flatten_claim();
                flat_claim.mix_into::<MC>(channel);
            }

            pub fn accumulate_relation_uses(
                &self,
                relation_uses: &mut RelationUsesDict,
            ) {
                $(accumulate_body)
            }

            pub fn log_sizes(&self) -> TreeVec<Vec<u32>> {
                let mut log_sizes_list = vec![];
                $(log_sizes_body)
                TreeVec::concat_cols(log_sizes_list.into_iter())
            }

            pub fn flatten_claim(&self) -> FlatClaim {
                let mut component_enable_bits = vec![];
                let mut component_log_sizes = vec![];

                $(flatten_claim_body)

                FlatClaim {
                    component_enable_bits,
                    component_log_sizes,
                    public_data: self.public_data.clone(),
                }
            }
        }
    }
}
