use air_compile::compiled_structs::CompiledAirFn;
use convert_case::{Case, Casing};
use genco::lang::rust;
use genco::quote;
use indexmap::IndexMap;
use itertools::Itertools;

use crate::utils::AUTOGENERATED_CODE_COMMENT;

pub fn generate_components_rust_file(
    compiled_registry: &IndexMap<String, CompiledAirFn>,
) -> rust::Tokens {
    let components_names: Vec<&String> = compiled_registry.keys().collect();
    quote! {
        $(AUTOGENERATED_CODE_COMMENT.to_string())
        use std::fmt::Display;
        use stwo::core::air::Component;
        use stwo_constraint_framework::preprocessed_columns::PreProcessedColumnId;
        use stwo_constraint_framework::TraceLocationAllocator;

        use crate::claims::{CairoClaim, CairoInteractionClaim};
        use crate::components::{$(&components_names.iter().join(", "))};
        use crate::relations::CommonLookupElements;
        use crate::components::indented_component_display;

        pub struct CairoComponents {
            $(&components_names.iter().map(|name| {
                if *name == "memory_id_to_big" {
                    format!("pub {name}: Vec<{name}::BigComponent>")
                } else {
                    format!("pub {name}: Option<{name}::Component>")
                }
            }).collect_vec().join(", "))
        }

        $(generate_cairo_components_impl(compiled_registry))
    }
}

fn generate_cairo_components_impl(
    compiled_registry: &IndexMap<String, CompiledAirFn>,
) -> rust::Tokens {
    let component_names: Vec<&String> = compiled_registry.keys().collect();
    let mut new_function_body = rust::Tokens::new();
    let mut components_function_body = rust::Tokens::new();
    let mut display_body = rust::Tokens::new();

    for &name in &component_names {
        let air_fn = &compiled_registry[name];
        // Special handling for memory_id_to_big.
        if *name == "memory_id_to_big" {
            new_function_body.append(quote! {
                let memory_id_to_big_component = memory_id_to_big::big_components_from_claim(
                    &cairo_claim.$(name).as_ref().unwrap().big_log_sizes,
                    &interaction_claim.$(name).as_ref().unwrap().big_claimed_sums,
                    &common_lookup_elements.clone(),
                    tree_span_provider,
                );
            });

            components_function_body.append(quote! {
                for component in &self.$(name) {
                    vec.push(component as &dyn Component);
                }
            });

            display_body.append(quote! {
                for component in &self.$(name) {
                    writeln!(
                        f,
                        "MemoryIdToValue: {}",
                        indented_component_display(component)
                    )?;
                }
            });
        } else {
            let mut segment_start_init = rust::Tokens::new();
            for public_param in &air_fn.public_params {
                segment_start_init.append(quote! {
                    $(public_param): cairo_claim
                    .public_data
                    .public_memory
                    .public_segments
                    .get_segment_range_by_name($(format!("\"{name}\"")))
                    .unwrap()
                    .start_ptr.value,
                });
            }
            new_function_body.append(quote! {
                let $(format!("{}_component", name)) = cairo_claim.$(name).map(|$(name)| {
                    $(name)::Component::new(
                        tree_span_provider,
                        $(name)::Eval {
                            claim: $(name),
                            common_lookup_elements: common_lookup_elements.clone(),
                            $(segment_start_init)
                        },
                        interaction_claim.$(name).unwrap().claimed_sum,
                    )
                });
            });

            components_function_body.append(quote! {
                if let Some(component) = &self.$(name) {
                    vec.push(component as &dyn Component);
                }
            });

            display_body.append(quote! {
                if let Some(ref component) = self.$(name) {
                    writeln!(
                        f,
                        $(&format!("\"{}: {{}}\"", name.to_case(Case::Pascal))),
                        indented_component_display(component)
                    )?;
                }
            });
        }
    }

    quote! {
        impl CairoComponents {
            pub fn new(
                cairo_claim: &CairoClaim,
                common_lookup_elements: &CommonLookupElements,
                interaction_claim: &CairoInteractionClaim,
                $("// Describes the structure of the preprocessed trace. Sensitive to order.")
                preprocessed_column_ids: &[PreProcessedColumnId],
            ) -> Self {
                let tree_span_provider =
                    &mut TraceLocationAllocator::new_with_preprocessed_columns(preprocessed_column_ids);

                $(new_function_body)

                Self {
                    $(&component_names.iter().map(|name| {
                        format!("{name}: {name}_component")
                    }).collect_vec().join(", "))
                }
            }

            pub fn components(&self) -> Vec<&dyn Component> {
                let mut vec: Vec<&dyn Component> = vec![];
                $(components_function_body)
                vec
            }
        }

        impl Display for CairoComponents {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                writeln!(f, "CairoComponents")?;
                $(display_body)
                Ok(())
            }
        }
    }
}
