use genco::lang::rust;
use genco::quote;

use crate::utils::AUTOGENERATED_CODE_COMMENT;

pub fn generate_provers_rust_file(components_names: &Vec<&String>) -> rust::Tokens {
    let mut provers_impl = rust::Tokens::new();
    for &name in components_names {
        // Special handling for memory_id_to_big: it has multiple sub-provers.
        if *name == "memory_id_to_big" {
            provers_impl.append(quote! {
                for component in &components.memory_id_to_big {
                    vec.push(component as &dyn ComponentProver<SimdBackend>);
                }
            });
        } else {
            provers_impl.append(quote! {
                if let Some(component) = &components.$(name) {
                    vec.push(component as &dyn ComponentProver<SimdBackend>);
                }
            });
        }
    }

    quote! {
        $(AUTOGENERATED_CODE_COMMENT.to_string())
        use stwo::prover::backend::simd::SimdBackend;
        use cairo_air::cairo_components::CairoComponents;
        use stwo::prover::ComponentProver;

        pub fn cairo_provers(components: &CairoComponents) -> Vec<&dyn ComponentProver<SimdBackend>> {
            let mut vec: Vec<&dyn ComponentProver<SimdBackend>> = vec![];
            $(provers_impl)
            vec
        }
    }
}
