[workspace]
# Using version 2 to avoid unifying features. For more info, read:
#   https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = ["crates/air_code_gen", "crates/air_infra"]

[workspace.package]
version = "0.1.0"
edition = "2021"


[workspace.dependencies]
serde = "1.0.196"
serde_json = "1.0.113"
num-integer = "0.1.46"
genco = "0.17.8"
xshell = "0.2.5"
stwo-prover = { git = "https://github.com/starkware-libs/stwo", branch = "dev" }
