[workspace]
# Using version 2 to avoid unifying features. For more info, read:
#   https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
    "crates/air_code_gen",
    "crates/air_infra",
    "crates/generated_components",
    "crates/derive_macros/inst_def",
    "crates/compiled_casm_air",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
genco = "0.17.8"
itertools = "0.12.1"
num-integer = "0.1.46"
num-traits = "0.2.18"
prover_types = { git = "https://github.com/starkware-libs/stwo-cairo.git", rev = "3cff5e1" }
serde = "1.0.196"
serde_json = "1.0.113"
starknet-ff = "0.3.7"
stwo-cairo-serialize = { git = "https://github.com/starkware-libs/stwo-cairo.git", rev = "3cff5e1" }
stwo-prover = { git = "https://github.com/starkware-libs/stwo", rev = "060f0e4" }
xshell = "0.2.5"
indexmap = "2.2.6"
convert_case = "0.6.0"
