[package]
name = "eval_air_fn_constraints"
version.workspace = true
edition.workspace = true

[dependencies]
compiled_casm_air = { path = "../compiled_casm_air" }
indexmap.workspace = true
num-traits.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
stwo-cairo-common.workspace = true
