use air_infra::airs::casm::casm_registry::{
    create_casm_registry, get_all_builtins, get_all_opcodes, get_sub_components,
};
use compiled_casm_air::compiled_structs::{CompiledAirFn, TraceType};
use convert_case::{Case, Casing};
use genco::lang::rust;
use genco::quote;
use indexmap::IndexMap;
use itertools::Itertools;

use crate::utils::{is_const_size_component, is_state_component_name, AUTOGENERATED_CODE_COMMENT};

pub fn generate_cairo_claim_generator_file() -> rust::Tokens {
    let registry = create_casm_registry();
    let mut compiled_regisry: IndexMap<String, CompiledAirFn> = registry
        .compile()
        .into_iter()
        .filter(|(_, compiled_air_fn)| {
            compiled_air_fn.r#type != TraceType::Const
                && compiled_air_fn.r#type != TraceType::Inline
        })
        .collect();

    // Ensure each component appears before all its dependencies.
    compiled_regisry.reverse();

    let claim_generator_struct =
        generate_cairo_claim_generator_struct(&compiled_regisry.keys().collect_vec());

    let fill_cairo_claim_generator = generate_fill_components(&compiled_regisry);

    let get_sub_components = generate_get_sub_components();

    quote! {
        $(AUTOGENERATED_CODE_COMMENT.to_string())
        use std::sync::Arc;
        use cairo_air::air::PublicData;
        use indexmap::IndexSet;
        use stwo_cairo_adapter::builtins::BuiltinSegments;
        use stwo_cairo_adapter::memory::Memory;
        use stwo_cairo_adapter::opcodes::CasmStatesByOpcode;
        use stwo_cairo_common::builtins::*;
        use stwo_cairo_common::preprocessed_columns::preprocessed_trace::PreProcessedTrace;
        use crate::witness::components::*;
        $['\n']
        $(claim_generator_struct)
        $['\n']
        $(fill_cairo_claim_generator)
        $['\n']
        $(get_sub_components)
        $['\n']
    }
}

fn generate_cairo_claim_generator_struct(all_components: &Vec<&String>) -> rust::Tokens {
    let mut fields = rust::Tokens::new();
    fields.append(quote! {
        pub public_data: PublicData,
    });
    for component_name in all_components {
        fields.append(quote! {
            pub $(*component_name): Option<$(*component_name)::ClaimGenerator>,
        });
    }

    quote! {
        #[derive(Default)]
        pub struct CairoClaimGenerator {
            $(fields)
        }
    }
}

fn generate_fill_components(compiled_regisry: &IndexMap<String, CompiledAirFn>) -> rust::Tokens {
    let mut function_body = rust::Tokens::new();

    for (name, compile_air_fn) in compiled_regisry {
        let (args, builtin_init_code) = match compile_air_fn.r#type {
            TraceType::Builtin => {
                let constant_name_str = name.to_case(Case::Constant) + "_MEMORY_CELLS";
                let init_code = quote! {
                    let segment = builtin_segments.$(name).unwrap();

                    let segment_length = segment.stop_ptr - segment.begin_addr;
                    assert!(
                        segment_length.is_multiple_of($(&constant_name_str)),
                        $(format!("\"{} segment length is not a multiple of it's cells_per_instance\"", name))
                    );

                    let n_instances = segment_length / $(constant_name_str);
                    assert!(
                        n_instances.is_power_of_two(),
                        $(format!("\"{} instances number is not a power of two\"", name))
                    );
                };

                (
                    quote! { n_instances.ilog2(), segment.begin_addr as u32 },
                    init_code,
                )
            }
            TraceType::Opcode => (
                quote! { casm_states_by_opcode.$(name) },
                rust::Tokens::new(),
            ),
            _ => {
                if is_const_size_component(compile_air_fn) {
                    (quote! { preprocessed_trace.clone() }, rust::Tokens::new())
                } else if is_state_component_name(name) {
                    (quote! { memory.clone() }, rust::Tokens::new())
                } else {
                    (rust::Tokens::new(), rust::Tokens::new())
                }
            }
        };

        function_body.append(quote! {
            self.$(name) = components.contains($(format!("&\"{}\"", &name))).then(|| {
                $(builtin_init_code)
                $(name)::ClaimGenerator::new($(args))
            });
        });
    }

    quote! {
        impl CairoClaimGenerator {
        #[allow(clippy::redundant_closure)]
        pub fn fill_components(
            &mut self,
            components: &IndexSet<&str>,
            casm_states_by_opcode: CasmStatesByOpcode,
            builtin_segments: &BuiltinSegments,
            memory: Arc<Memory>,
            preprocessed_trace: Arc<PreProcessedTrace>,
        ){
            $(function_body)
        }
    }
    }
}

fn generate_get_sub_components() -> rust::Tokens {
    let all_components: IndexMap<String, Vec<String>> = get_all_opcodes()
        .iter()
        .map(|opcode| (opcode.name(), get_sub_components(opcode.as_ref())))
        .chain(
            get_all_builtins()
                .iter()
                .map(|builtin| (builtin.name(), get_sub_components(builtin.as_ref()))),
        )
        .collect();

    let mut match_code = rust::Tokens::new();
    for (name, sub_components) in all_components.iter() {
        match_code.append(quote! {
            $(format!("\"{}\"", name)) => {
                vec![$(sub_components
                    .iter()
                    .map(|component| format!("\"{}\"", component))
                    .join(", "))]
            }
        });
    }

    quote! {
        pub fn get_sub_components(component_name: &str) -> Vec<&'static str> {
            match component_name {
                $(match_code)
                _ => panic!("Unknown component: {component_name}"),
            }
        }
    }
}
