use compiled_casm_air::compiled_structs::CompiledAirFn;
use genco::lang::rust;
use genco::quote;
use indexmap::IndexMap;
use itertools::Itertools;

use crate::utils::{is_const_size_component, AUTOGENERATED_CODE_COMMENT};

pub fn generate_claims_rust_file(
    compiled_regisry: &IndexMap<String, CompiledAirFn>,
) -> rust::Tokens {
    let components_names = compiled_regisry.keys().collect_vec();

    let cairo_claim_impl = generate_cairo_claim_impl(compiled_regisry);

    quote! {
        $(AUTOGENERATED_CODE_COMMENT.to_string())
        use num_traits::Zero;
        use serde::{Deserialize, Serialize};
        use stwo::core::channel::Channel;
        use stwo::core::fields::qm31::QM31;
        use stwo_cairo_serialize::{CairoDeserialize, CairoSerialize};
        use crate::air::{
            accumulate_relation_memory, accumulate_relation_uses, PublicData, RelationUsesDict,
        };
        use crate::claims::prelude::SecureField;
        use crate::components::*;
        use crate::relations::CommonLookupElements;

        #[derive(Clone, Serialize, Deserialize, CairoSerialize, CairoDeserialize)]
        pub struct CairoClaim {
            pub public_data: PublicData,
            $(&components_names.iter().map(|name| {
                format!("pub {name}: Option<{name}::Claim>")
            }).collect_vec().join(", "))
        }

        $(cairo_claim_impl)

        #[derive(Clone, Serialize, Deserialize, CairoSerialize, CairoDeserialize)]
        pub struct CairoInteractionClaim {
            $(&components_names.iter().map(|name| {
                format!("pub {name}: Option<{name}::InteractionClaim>")
            }).collect_vec().join(", "))
        }

        impl CairoInteractionClaim {
            pub fn mix_into(&self, channel: &mut impl Channel) {
                $(&components_names.iter().map(|name| {
                    format!("self.{name}.as_ref().inspect(|c| c.mix_into(channel));")
                }).collect_vec().join("\n"));
            }
        }

        // TODO(Stav): change it to be a sum function of the CairoInteractionClaim.
        pub fn lookup_sum(
            claim: &CairoClaim,
            common_lookup_elements: &CommonLookupElements,
            interaction_claim: &CairoInteractionClaim,
        ) -> SecureField {
            let mut sum = QM31::zero();
            sum += claim.public_data.logup_sum(common_lookup_elements);
            $(&components_names.iter().map(|name| {
                format!("interaction_claim.{name}.as_ref().inspect(|ic| {{sum += ic.claimed_sum;}});")
            }).collect_vec().join("\n"));
            sum
        }
    }
}

fn generate_cairo_claim_impl(compiled_regisry: &IndexMap<String, CompiledAirFn>) -> rust::Tokens {
    let mut mix_into_body = rust::Tokens::new();
    let mut accumulate_body = rust::Tokens::new();

    for (name, compiled_air_fn) in compiled_regisry {
        // Add to mix_into() body.
        mix_into_body.append(quote! {
            channel.mix_u64(self.$(name).is_some() as u64);
            self.$(name).as_ref().inspect(|c| c.mix_into(channel));
        });

        // Add to accumulate_relation_uses() body.
        if name == "memory_id_to_big" {
            accumulate_body.append(quote! {
                accumulate_relation_memory(
                    relation_uses,
                    &self.$(name),
                );
            });
        } else if !is_const_size_component(compiled_air_fn) {
            accumulate_body.append(quote! {
                self.$(name).as_ref().inspect(|c| {
                    accumulate_relation_uses(
                        relation_uses,
                        $(name)::RELATION_USES_PER_ROW,
                        c.log_size,
                    )
                });
            });
        }
    }

    quote! {
        impl CairoClaim {
            pub fn mix_into(&self, channel: &mut impl Channel) {
                self.public_data.mix_into(channel);
                $(mix_into_body)
            }

            pub fn accumulate_relation_uses(
                &self,
                relation_uses: &mut RelationUsesDict,
            ) {
                $(accumulate_body)
            }

        }
    }
}
