use compiled_casm_air::compiled_structs::CompiledAirFn;
use genco::lang::rust;
use genco::quote;
use indexmap::IndexMap;
use itertools::Itertools;

use crate::utils::{is_const_size_component, AUTOGENERATED_CODE_COMMENT};

pub fn generate_claims_rust_file(
    compiled_regisry: &IndexMap<String, CompiledAirFn>,
) -> rust::Tokens {
    let components_names = compiled_regisry.keys().collect_vec();

    quote! {
        $(AUTOGENERATED_CODE_COMMENT.to_string())
        use num_traits::Zero;
        use serde::{Deserialize, Serialize};
        use stwo::core::channel::Channel;
        use stwo::core::fields::qm31::SecureField;
        use stwo_cairo_serialize::{CairoDeserialize, CairoSerialize};
        use crate::air::{
            accumulate_relation_memory, accumulate_relation_uses, PublicData, RelationUsesDict,
        };
        use stwo::core::pcs::TreeVec;
        use crate::components::*;
        use crate::relations::CommonLookupElements;
        use super::flat_claims::{FlatClaim, flatten_interaction_claim};

        #[derive(Clone, Serialize, Deserialize, CairoSerialize, CairoDeserialize)]
        pub struct CairoClaim {
            pub public_data: PublicData,
            $(&components_names.iter().map(|name| {
                format!("pub {name}: Option<{name}::Claim>")
            }).collect_vec().join(", "))
        }

        $(generate_cairo_claim_impl(compiled_regisry))

        #[derive(Clone, Serialize, Deserialize, CairoSerialize, CairoDeserialize)]
        pub struct CairoInteractionClaim {
            $(&components_names.iter().map(|name| {
                format!("pub {name}: Option<{name}::InteractionClaim>")
            }).collect_vec().join(", "))
        }

        impl CairoInteractionClaim {
            pub fn mix_into(&self, channel: &mut impl Channel) {
                let claim = flatten_interaction_claim(self);
                channel.mix_felts(claim.as_slice());
            }
        }

        // TODO(Stav): change it to be a sum function of the CairoInteractionClaim.
        pub fn lookup_sum(
            claim: &CairoClaim,
            common_lookup_elements: &CommonLookupElements,
            interaction_claim: &CairoInteractionClaim,
        ) -> SecureField {
            let mut sum = SecureField::zero();
            sum += claim.public_data.logup_sum(common_lookup_elements);
            $(&components_names.iter().map(|name| {
                format!("interaction_claim.{name}.as_ref().inspect(|ic| {{sum += ic.claimed_sum;}});")
            }).collect_vec().join("\n"));
            sum
        }
    }
}

fn generate_cairo_claim_impl(compiled_regisry: &IndexMap<String, CompiledAirFn>) -> rust::Tokens {
    let mut accumulate_body = rust::Tokens::new();
    let mut log_sizes_body = rust::Tokens::new();

    for (name, compiled_air_fn) in compiled_regisry {
        // Add to accumulate_relation_uses() body.
        if name == "memory_id_to_big" {
            accumulate_body.append(quote! {
                accumulate_relation_memory(
                    relation_uses,
                    &self.$(name),
                );
            });
        } else if !is_const_size_component(compiled_air_fn) {
            accumulate_body.append(quote! {
                self.$(name).as_ref().inspect(|c| {
                    accumulate_relation_uses(
                        relation_uses,
                        $(name)::RELATION_USES_PER_ROW,
                        c.log_size,
                    )
                });
            });
        }

        log_sizes_body.append(quote! {
            self.$(name).as_ref().inspect(|c| log_sizes_list.push(c.log_sizes()));
        });
    }

    quote! {
        impl CairoClaim {
            pub fn mix_into(&self, channel: &mut impl Channel) {
                let claim = FlatClaim::from_cairo_claim(self);
                claim.mix_into(channel);
            }

            pub fn accumulate_relation_uses(
                &self,
                relation_uses: &mut RelationUsesDict,
            ) {
                $(accumulate_body)
            }

            pub fn log_sizes(&self) -> TreeVec<Vec<u32>> {
                let mut log_sizes_list = vec![];
                $(log_sizes_body)
                TreeVec::concat_cols(log_sizes_list.into_iter())
            }
        }
    }
}
