use air_compile::compiled_structs::CompiledAirFn;
use genco::lang::rust;
use genco::quote;
use indexmap::IndexMap;
use itertools::Itertools;

use crate::utils::{is_const_size_component, AUTOGENERATED_CODE_COMMENT};

pub fn generate_claims_cairo_file(
    compiled_regisry: &IndexMap<String, CompiledAirFn>,
) -> rust::Tokens {
    let components_names = compiled_regisry.keys().collect_vec();

    quote! {
        $(AUTOGENERATED_CODE_COMMENT.to_string())
        use core::num::traits::Zero;
        use stwo_cairo_air::claim::ClaimTrait;
        use stwo_cairo_air::{PublicData, PublicDataImpl, RelationUsesDict};
        use stwo_constraint_framework::CommonLookupElements;
        use stwo_verifier_core::TreeArray;
        use stwo_verifier_core::channel::Channel;
        use stwo_verifier_core::fields::qm31::QM31;
        use stwo_verifier_core::utils::OptionImpl;
        $(&components_names.iter().map(|name| {
            format!("use crate::components::{name};")
        }).collect_vec().join("\n"))
        use crate::{ChannelTrait, PublicDataTrait, components};
        use super::claim::{FlatClaim, FlatClaimTrait};
        use crate::cairo_air::override_preprocessed_trace_log_sizes;
        use crate::utils::tree_array_concat_cols;
        use crate::components::memory_address_to_id::MEMORY_ADDRESS_TO_ID_SPLIT;


        #[derive(Drop, Serde)]
        pub struct CairoClaim {
            pub public_data: PublicData,
            $(&components_names.iter().map(|name| {
                format!("pub {name}: Option<components::{name}::Claim>")
            }).collect_vec().join(", "))
        }

        $(generate_cairo_claim_impl(compiled_regisry))

        #[derive(Drop, Serde)]
        pub struct CairoInteractionClaim {
            $(&components_names.iter().map(|name| {
                format!("pub {name}: Option<components::{name}::InteractionClaim>")
            }).collect_vec().join(", "))
        }

        $(generate_cairo_interaction_claim_impl(&components_names))

        // TODO(Stav): change it to be a sum function of the CairoInteractionClaim.
        pub fn lookup_sum(
            claim: @CairoClaim,
            elements: @CommonLookupElements,
            interaction_claim: @CairoInteractionClaim,
        ) -> QM31 {
            let mut sum = claim.public_data.logup_sum(elements);
            $(&components_names.iter().map(|name| {
                format!("if let Some(interaction_claim) = interaction_claim.{name} {{sum += *interaction_claim.claimed_sum;}}")
            }).collect_vec().join("\n"));
            sum
        }
    }
}

fn generate_cairo_claim_impl(compiled_regisry: &IndexMap<String, CompiledAirFn>) -> rust::Tokens {
    let mut accumulate_body = rust::Tokens::new();
    let mut log_sizes_body = rust::Tokens::new();
    let mut flatten_claim_body = rust::Tokens::new();

    for (name, compiled_air_fn) in compiled_regisry {
        // Add to accumulate_relation_uses() body.
        if !is_const_size_component(compiled_air_fn) {
            accumulate_body.append(quote! {
                if let Some(claim) = self.$(name) {
                    claim.accumulate_relation_uses(ref relation_uses);
                }
            });
        }

        // Add to log_sizes() body.
        log_sizes_body.append(quote! {
            if let Some(claim) = self.$(name) {
                log_sizes_list.append(claim.log_sizes());
            }
        });

        // Add to flatten_claim() body.
        if name == "memory_id_to_big" {
            flatten_claim_body.append(quote! {
                let memory_id_to_big::Claim {
                    big_log_sizes,
                } = self.memory_id_to_big.as_snap().unwrap();
                assert!(big_log_sizes.len() <= MEMORY_ADDRESS_TO_ID_SPLIT);
                for log_size in big_log_sizes {
                    component_log_sizes.append(*log_size);
                    component_enable_bits.append(true);
                }
                for _ in 0..(MEMORY_ADDRESS_TO_ID_SPLIT - big_log_sizes.len()) {
                    component_log_sizes.append(0_u32);
                    component_enable_bits.append(false);
                }
            });
        } else {
            let (claim_binding, log_size_expr) = if is_const_size_component(compiled_air_fn) {
                (quote! { _c }, quote! { $(name)::LOG_SIZE })
            } else {
                (quote! { c }, quote! { *c.log_size })
            };
            flatten_claim_body.append(quote! {
                if let Some($(claim_binding)) = self.$(name) {
                    component_log_sizes.append($(log_size_expr));
                    component_enable_bits.append(true);
                } else {
                    component_log_sizes.append(0_u32);
                    component_enable_bits.append(false);
                }
            });
        }
    }

    quote! {
        pub impl CairoClaimImpl of ClaimTrait<CairoClaim> {
            fn log_sizes(self: @CairoClaim) -> TreeArray<Span<u32>> {
                let mut log_sizes_list = array![];
                $(log_sizes_body)
                let aggregated_log_sizes = tree_array_concat_cols(log_sizes_list);
                override_preprocessed_trace_log_sizes(aggregated_log_sizes)
            }

            fn mix_into(self: @CairoClaim, ref channel: Channel) {
                let flat_claim = self.flatten_claim();
                flat_claim.mix_into(ref channel);
            }

            fn accumulate_relation_uses(self: @CairoClaim, ref relation_uses: RelationUsesDict) {
                $(accumulate_body)
            }
        }

        #[generate_trait]
        pub impl CairoClaimFlattenImpl of CairoClaimFlattenTrait {
            $("/// Create flat claim out of the given claim.")
            fn flatten_claim(self: @CairoClaim) -> FlatClaim {
                let mut component_enable_bits = array![];
                let mut component_log_sizes = array![];

                $(flatten_claim_body)

                FlatClaim {
                    component_enable_bits: component_enable_bits.span(),
                    component_log_sizes: component_log_sizes.span(),
                    public_data: self.public_data.clone(),
                }
            }
        }
    }
}

/// Generates the CairoInteractionClaim impl with flatten_interaction_claim method.
pub fn generate_cairo_interaction_claim_impl(components_names: &Vec<&String>) -> rust::Tokens {
    let mut flatten_interaction_body = rust::Tokens::new();

    for &name in components_names {
        // Special handling for memory_id_to_big.
        if name == "memory_id_to_big" {
            flatten_interaction_body.append(quote! {
                let memory_id_to_big::InteractionClaim {
                    big_claimed_sums, claimed_sum: _,
                } = self.memory_id_to_big.as_snap().unwrap();
                assert!(big_claimed_sums.len() <= MEMORY_ADDRESS_TO_ID_SPLIT);
                for claimed_sum in big_claimed_sums {
                    claimed_sums.append(*claimed_sum);
                }
                for _ in 0..(MEMORY_ADDRESS_TO_ID_SPLIT - big_claimed_sums.len()) {
                    claimed_sums.append(Zero::zero());
                }
            });
        } else {
            flatten_interaction_body.append(quote! {
                if let Some(c) = self.$(name) {
                    claimed_sums.append(*c.claimed_sum);
                } else {
                    claimed_sums.append(Zero::zero());
                }
            });
        }
    }

    quote! {
        #[generate_trait]
        pub impl CairoInteractionClaimImpl of CairoInteractionClaimTrace {
            fn mix_into(self: @CairoInteractionClaim, ref channel: Channel) {
                let claim = self.flatten_interaction_claim();
                channel.mix_felts(claim);
            }

            $("/// Extracts the claimed sums from a [CairoInteractionClaim].")
            $("/// Returns a vector of all claimed sums for the logup argument, one per component.")
            $("/// The order must match the order of components as they appear in")
            $("/// [cairo_air::air::CairoComponents].")
            fn flatten_interaction_claim(
                self: @CairoInteractionClaim,
            ) -> Span<QM31> {
                let mut claimed_sums = array![];

                $(flatten_interaction_body)

                claimed_sums.span()
            }
        }
    }
}
