use compiled_casm_air::compiled_structs::CompiledAirFn;
use convert_case::{Case, Casing};
use genco::lang::rust;
use genco::quote;
use indexmap::IndexMap;
use itertools::Itertools;

use crate::utils::{is_const_size_component, AUTOGENERATED_CODE_COMMENT};

pub fn generate_claims_cairo_file(
    compiled_regisry: &IndexMap<String, CompiledAirFn>,
) -> rust::Tokens {
    let components_names = compiled_regisry.keys().collect_vec();

    let cairo_claim_impl = generate_cairo_claim_impl(compiled_regisry);

    quote! {
        $(AUTOGENERATED_CODE_COMMENT.to_string())
        use stwo_cairo_air::claim::ClaimTrait;
        use stwo_cairo_air::{PublicData, PublicDataImpl, RelationUsesDict};
        use stwo_constraint_framework::CommonLookupElements;
        use stwo_verifier_core::TreeArray;
        use stwo_verifier_core::channel::Channel;
        use stwo_verifier_core::fields::qm31::QM31;
        use stwo_verifier_core::utils::OptionImpl;
        use crate::cairo_air::log_sizes;
        $(&components_names.iter().map(|name| {
            let alias = format!("{}InteractionClaimImpl", name.to_case(Case::Pascal));
            format!("use crate::components::{name}::InteractionClaimImpl as {alias};")
        }).collect_vec().join("\n"))
        use crate::{ChannelTrait, PublicDataTrait, components};

        #[derive(Drop, Serde)]
        pub struct CairoClaim {
            pub public_data: PublicData,
            $(&components_names.iter().map(|name| {
                format!("pub {name}: Option<components::{name}::Claim>")
            }).collect_vec().join(", "))
        }

        $(cairo_claim_impl)

        #[derive(Drop, Serde)]
        pub struct CairoInteractionClaim {
            $(&components_names.iter().map(|name| {
                format!("pub {name}: Option<components::{name}::InteractionClaim>")
            }).collect_vec().join(", "))
        }

        #[generate_trait]
        pub impl CairoInteractionClaimImpl of CairoInteractionClaimTrace {
            fn mix_into(self: @CairoInteractionClaim, ref channel: Channel) {
                $(&components_names.iter().map(|name| {
                    format!("if let Some(claim) = self.{name} {{claim.mix_into(ref channel);}}")
                }).collect_vec().join("\n"))
            }
        }

        // TODO(Stav): change it to be a sum function of the CairoInteractionClaim.
        pub fn lookup_sum(
            claim: @CairoClaim,
            elements: @CommonLookupElements,
            interaction_claim: @CairoInteractionClaim,
        ) -> QM31 {
            let mut sum = claim.public_data.logup_sum(elements);
            $(&components_names.iter().map(|name| {
                format!("if let Some(interaction_claim) = interaction_claim.{name} {{sum += *interaction_claim.claimed_sum;}}")
            }).collect_vec().join("\n"));
            sum
        }
    }
}

fn generate_cairo_claim_impl(compiled_regisry: &IndexMap<String, CompiledAirFn>) -> rust::Tokens {
    let mut mix_into_body = rust::Tokens::new();
    let mut accumulate_body = rust::Tokens::new();

    // Generate public_data.mix_into
    mix_into_body.append(quote! {
        self.public_data.mix_into(ref channel);
    });

    for (name, compiled_air_fn) in compiled_regisry {
        // Add to mix_into() body with Option handling
        mix_into_body.append(quote! {
            if let Some(claim) = self.$(name) {
                channel.mix_u64(1);
                claim.mix_into(ref channel);
            } else {
                channel.mix_u64(0);
            }
        });

        // Add to accumulate_relation_uses() body
        if !is_const_size_component(compiled_air_fn) {
            accumulate_body.append(quote! {
                if let Some(claim) = self.$(name) {
                    claim.accumulate_relation_uses(ref relation_uses);
                }
            });
        }
    }

    quote! {
        pub impl CairoClaimImpl of ClaimTrait<CairoClaim> {
            fn log_sizes(self: @CairoClaim) -> TreeArray<Span<u32>> {
                log_sizes(self)
            }

            fn mix_into(self: @CairoClaim, ref channel: Channel) {
                $(mix_into_body)
            }

            fn accumulate_relation_uses(self: @CairoClaim, ref relation_uses: RelationUsesDict) {
                $(accumulate_body)
            }
        }
    }
}
