use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::str::from_utf8;

use compiled_casm_air::compiled_structs::{CompiledAirFn, CompiledAirVar, TraceType};
use compiled_casm_air::utils::{read_json, SAMPLE_EVALUATIONS_FILE_NAME};
use eval_air_fn_constraints::SampleEvaluation;
use genco::lang::rust;
use genco::quote;
use indexmap::{IndexMap, IndexSet};
use xshell::{cmd, Shell};

use crate::components_code_gen::cairo_constraints::utils::{
    format_cairo_code, generate_cairo_constraints_code,
};
use crate::components_code_gen::constraints::generate_constraints_code;
use crate::components_code_gen::supported_components::{AutogenCodeFile, AutogenCodeType};
use crate::components_code_gen::trace_gen::RustProverGen;

pub const AUTOGENERATED_CODE_COMMENT: &str = "// This file was created by the AIR team.\n\n";

/// Load compiled AirFns and the associated sample evaluations.
///
/// `root_dir` is the directory that contains the sample evaluations file. All
/// AirFns are supposed to be under `<root_dir>/components`, but this is not checked.
pub fn load_air_fns(
    root_dir: &Path,
    jobs: &[AutogenCodeFile],
) -> (
    IndexMap<String, CompiledAirFn>,
    IndexMap<String, SampleEvaluation>,
) {
    let mut air_fns = IndexMap::new();
    for job in jobs {
        if air_fns.contains_key(&job.air_fn_name) {
            continue;
        }
        let compiled_air_fn: CompiledAirFn =
            serde_json::from_value(read_json(job.source_path.to_str().expect("Invalid path")))
                .unwrap_or_else(|err| {
                    panic!("Invalid AirFn in {}: {err}", job.source_path.display())
                });
        air_fns.insert(job.air_fn_name.clone(), compiled_air_fn);
    }

    let sample_evaluations = serde_json::from_value(read_json(
        root_dir
            .join(SAMPLE_EVALUATIONS_FILE_NAME)
            .to_str()
            .expect("Invalid directory name"),
    ))
    .unwrap_or_else(|e| panic!("Invalid sample evaluations file: {e}"));

    (air_fns, sample_evaluations)
}

pub fn project_root() -> PathBuf {
    std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap())
}

pub fn reformat_rust_code(code_text: String) -> String {
    // Since rustfmt is used with nightly features, it takes 2 runs to reach a fixed point.
    reformat_rust_code_inner(reformat_rust_code_inner(code_text))
}

pub fn reformat_rust_code_inner(code_text: String) -> String {
    let shell = Shell::new().unwrap();
    shell.set_var("RUSTUP_TOOLCHAIN", "nightly-2025-07-14");
    let rustfmt_toml = project_root().join("../../rustfmt.toml");
    let mut stdout = cmd!(shell, "rustfmt --config-path {rustfmt_toml}")
        .stdin(code_text)
        .read()
        .unwrap();
    if !stdout.ends_with('\n') {
        stdout.push('\n');
    }
    stdout
}

pub fn get_git_rev(directory: &Path) -> String {
    let git_show_output = Command::new("git")
        .args([
            "-C",
            directory
                .to_str()
                .expect("The directory should be valid UTF-8"),
            "describe",
            "--always",
            "--dirty",
        ])
        .output()
        .unwrap();
    from_utf8(git_show_output.stdout.as_slice())
        .expect("Git output is valid UTF-8")
        .trim()
        .to_string()
}

/// Create the file `file_path` with the given content, and update the `mod.rs`
/// file in the same directory to include the new file.
pub fn add_file_to_module(file_path: &Path, file_content: String, code_type: AutogenCodeType) {
    let parent_dir = file_path
        .parent()
        .expect("path should include directory name");
    let (mod_file_path, mod_file_name) = match code_type {
        AutogenCodeType::WITNESS | AutogenCodeType::AIR => (parent_dir, "mod.rs".to_string()),
        AutogenCodeType::CAIRO => {
            let file_name = parent_dir
                .file_name()
                .expect("path should include directory name")
                .to_str()
                .expect("Invalid directory name");
            (
                parent_dir
                    .parent()
                    .expect("path should include parent directory name"),
                file_name.to_string() + ".cairo",
            )
        }
    };

    assert!(
        *file_path.file_name().unwrap() != *mod_file_name,
        "This function is not for adding the file {mod_file_name}"
    );

    // Read mod file contents
    let mod_file_path = mod_file_path.join(mod_file_name);

    let mut mod_file_content = match mod_file_path.exists() {
        true => fs::read_to_string(&mod_file_path)
            .unwrap_or_else(|_| panic!("Cannot read mod file {}", mod_file_path.to_string_lossy())),
        false => "".into(),
    };

    // Add mod file line for the new file
    let mod_file_line = &format!(
        "pub mod {};",
        file_path
            .file_stem()
            .expect("Invalid filename")
            .to_str()
            .expect("Invalid filename")
    );
    if !mod_file_content.contains(mod_file_line) {
        mod_file_content.push_str(mod_file_line);
        mod_file_content.push('\n');
    }

    // Write new file and updated mod file
    fs::write(file_path, file_content)
        .unwrap_or_else(|_| panic!("Failed to write file to path {}", file_path.display()));
    fs::write(&mod_file_path, mod_file_content)
        .unwrap_or_else(|_| panic!("Failed to write file to path {}", mod_file_path.display()));
}

pub fn generate_air_fn_code(
    air_fn: &CompiledAirFn,
    sample_evaluation: Option<&SampleEvaluation>,
    code_type: AutogenCodeType,
) -> String {
    let code = match code_type {
        AutogenCodeType::WITNESS => {
            // Witness code generation does not support inline functions
            assert!(air_fn.r#type != TraceType::Inline);
            RustProverGen::new(air_fn.clone()).generate_witness_code()
        }
        AutogenCodeType::AIR => generate_constraints_code(air_fn),
        AutogenCodeType::CAIRO => generate_cairo_constraints_code(air_fn, sample_evaluation),
    };

    AUTOGENERATED_CODE_COMMENT.to_string() + &code.to_string().unwrap()
}

pub fn format_air_fn_code(code: String, code_type: AutogenCodeType) -> String {
    match code_type {
        AutogenCodeType::WITNESS => reformat_rust_code(code),
        AutogenCodeType::AIR => reformat_rust_code(code),
        AutogenCodeType::CAIRO => format_cairo_code(code),
    }
}

pub fn generated_code_path(
    air_fn: &CompiledAirFn,
    dest_dir: &Path,
    code_type: AutogenCodeType,
) -> PathBuf {
    let dest_dir = match air_fn.r#type {
        TraceType::Inline => dest_dir.join("subroutines/"),
        _ => dest_dir.to_path_buf(),
    };

    let file_name = match code_type {
        AutogenCodeType::WITNESS | AutogenCodeType::AIR => format!("{}.rs", air_fn.name),
        AutogenCodeType::CAIRO => format!("{}.cairo", air_fn.name),
    };

    dest_dir.join(&file_name)
}

pub fn get_constraints_folder_path_suffix(r#type: &TraceType, file_name: &String) -> String {
    if r#type == &TraceType::Inline {
        format!("subroutines/{file_name}")
    } else {
        file_name.clone()
    }
}

// Removes trailing zeroes from a comma-separated sequence of M31 elements.
// Used to reduce 0 multiplications in the extension field.
pub fn remove_trailing_zeroes(felts: &[CompiledAirVar]) -> Vec<CompiledAirVar> {
    let mut felts = felts.to_vec();
    while felts
        .last()
        .is_some_and(|f| f.eq(&CompiledAirVar::Const("M31".to_string(), "0".to_string())))
    {
        felts.pop();
    }
    felts
}

pub fn get_variable_name(ty: &str, val: &str) -> String {
    format!("{ty}_{val}")
        .replace([',', '<', '['], "_")
        .replace("::", "_")
        .replace(['>', ']', ' ', ':'], "")
        .replace("__", "_")
}

pub fn make_preprocessed_column_id(id: &String) -> rust::Tokens {
    quote! { PreProcessedColumnId { id: $(format!("\"{}\"", id)).to_owned() } }
}

/// Replaces plain generics `<...>` with Turobofish `::<...>`.
/// Used where a function call is needed.
/// E.g. "BigUint<x, y, z>" -> "BigUint::<x, y, z>".
pub fn replace_generics_with_turbofish(ty: &str) -> String {
    ty.replace('<', "::<")
}

pub fn block_doc(msg: &str) -> rust::Tokens {
    quote! {
        $['\n']$("// ")$msg.$['\n']
    }
}

pub fn relations_used_or_yielded(air_fn: &CompiledAirFn) -> IndexSet<String> {
    // TODO(AnatG): Change the name of constraint_lookups in compiled air. This is used also in
    // trace_gen.
    air_fn
        .constraint_lookups
        .iter()
        .map(|(r, _)| r.clone())
        .collect::<IndexSet<_>>()
}

/// Checks if the relation should be masked, meaning it's numerator should be altered.
/// A relation is masked when the relation name matches one of the component's relation names (the
/// component must contain an enabler/multiplicity columns).
pub fn relation_multiplicity_index(air_fn: &CompiledAirFn, relation_name: &str) -> Option<usize> {
    air_fn
        .relation_names
        .iter()
        .position(|n| n == relation_name)
}

pub fn is_const_size_component(air_fn: &CompiledAirFn) -> bool {
    air_fn.log_height.is_some()
}

pub fn is_state_component_name(component_name: &str) -> bool {
    component_name == "blake_round"
        || component_name == "memory_address_to_id"
        || component_name == "memory_id_to_big"
}

#[cfg(test)]
mod tests {
    use genco::lang::rust;
    use genco::quote;

    use super::reformat_rust_code;

    #[test]
    fn test_reformat_rust_code() {
        let mut code = rust::Tokens::new();
        code.extend(quote! {
            fn foo() {
                println!("Hello, world!");
            }
        });
        let code_text = reformat_rust_code(code.to_string().expect("Could not format Rust code."));
        println!("{code_text}");
    }
}
