[package]
name = "generated_components"
version.workspace = true
edition.workspace = true

[dependencies]
itertools.workspace = true
num-traits.workspace = true
serde.workspace = true
starknet-ff.workspace = true
stwo-cairo-serialize = { git = "https://github.com/starkware-libs/stwo-cairo.git", rev = "53c4ea9" }
stwo-prover = { git = "https://github.com/starkware-libs/stwo", rev = "f24cde6" }
prover_types = { git = "https://github.com/starkware-libs/stwo-cairo.git", rev = "53c4ea9" }

[features]
default = []
fix_code = []

[dev-dependencies]
rand = { version = "0.8.5" }
