[package]
name = "generated_components"
version.workspace = true
edition.workspace = true

[dependencies]
stwo-prover = { git = "https://github.com/starkware-libs/stwo", rev = "264922e" }
prover_types = { git = "https://github.com/starkware-libs/stwo-cairo.git", rev = "e741515" }
itertools.workspace = true
num-traits.workspace = true
serde.workspace = true

[features]
default = []
fix_code = []

[dev-dependencies]
rand = { version = "0.8.5" }
