[package]
name = "witness"
version.workspace = true
edition.workspace = true

[dependencies]
num-traits.workspace = true
stwo.workspace = true
stwo-air-utils.workspace = true
stwo-air-utils-derive.workspace = true
stwo-cairo-common.workspace = true
stwo-constraint-framework = { workspace = true, features = ["parallel"] }
cairo_air = { path = "../cairo_air" }
rayon = "1.10.0"
