[package]
name = "air_infra"
version.workspace = true
edition.workspace = true

[features]
test = ["dep:eval_air_fn_constraints"]

[dependencies]
eval_air_fn_constraints = { path = "../eval_air_fn_constraints", optional = true }
air_common = { path = "../air_common" }
air_compile = { path = "../air_compile" }

serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
enum_dispatch = "0.3.13"
indexmap = { workspace = true, features = ["serde"] }
convert_case.workspace = true
regex = "1.11.1"

stwo-cairo-common.workspace = true

[dev-dependencies]
eval_air_fn_constraints = { path = "../eval_air_fn_constraints" }
generic-tests.workspace = true
expect-test = "1.4"
blake2 = "0.10.6"
