[package]
name = "air_infra"
version.workspace = true
edition.workspace = true

[features]
test = ["dep:eval_air_fn_constraints"]

[dependencies]
eval_air_fn_constraints = { workspace = true, optional = true }
air_common.workspace = true
air_compile.workspace = true

serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
enum_dispatch.workspace = true
indexmap = { workspace = true, features = ["serde", "std"] }
convert_case.workspace = true
regex.workspace = true

stwo-cairo-common.workspace = true

[dev-dependencies]
eval_air_fn_constraints.workspace = true
generic-tests.workspace = true
expect-test.workspace = true
blake2.workspace = true
