[package]
name = "airs"
version.workspace = true
edition.workspace = true

[dependencies]
air_common = { path = "../air_common" }
air_compile = { path = "../air_compile" }
air_infra = { path = "../air_infra" }

serde = { workspace = true, features = ["derive", "rc"] }
indexmap = { workspace = true, features = ["serde"] }
serde_arrays.workspace = true

stwo-cairo-common.workspace = true

[dev-dependencies]
air_infra = { path = "../air_infra", features = ["test"] }
generic-tests.workspace = true
expect-test = "1.4"
blake2 = "0.10.6"
