use std::path::Path;

use air_compile::compiled_structs::CompiledAirFn;
use genco::lang::rust;
use genco::quote;
use indexmap::IndexMap;

use crate::supported_components::AutogenCodeType;
use crate::utils::*;

pub fn generate_all_components_file(
    dest_dir: &Path,
    compiled_registry: &IndexMap<String, CompiledAirFn>,
) {
    let mut body = vec![];
    for (name, _) in compiled_registry.iter() {
        if name == "memory_id_to_big" {
            body.push(
                "(\"memory_id_to_big\", Box::new(components::memory_id_to_big::Component { index: \
                 0 }) as Box<dyn CircuitEval<Value>>)"
                    .to_string(),
            );
            // TODO(AnatG): Get this constant from stwo-cairo-common.
            for i in 1..16 {
                body.push(format!(
                    "(\"memory_id_to_big_{i}\", Box::new(components::memory_id_to_big::Component \
                     {{ index: {i} }}) as Box<dyn CircuitEval<Value>>)"
                ));
            }
        } else {
            body.push(format!(
                "(\"{name}\", Box::new(components::{name}::Component {{}}) as Box<dyn \
                 CircuitEval<Value>>)"
            ));
        }
    }

    let tokens: rust::Tokens = quote! {
        $AUTOGENERATED_CODE_COMMENT

        use indexmap::IndexMap;

        use circuits::ivalue::IValue;
        use circuits_stark_verifier::constraint_eval::CircuitEval;
        use crate::components;

        pub fn all_components<Value: IValue>() -> IndexMap<&'static str, Box<dyn CircuitEval<Value>>> {
            IndexMap::from([$(body.join(", "))])
        }
    };

    add_file_to_module(
        &dest_dir.join("all_components.rs"),
        tokens.to_string().unwrap(),
        &AutogenCodeType::CIRCUIT,
    );
}
