use super::generic_opcode::*;

use crate::airs::casm::casm_state::CasmStateVar;
use crate::airs::casm::common::*;
use crate::airs::casm::opcodes::assert_eq_opcode::*;
use crate::airs::casm::opcodes::call_opcode::*;
use crate::airs::casm::opcodes::jnz_opcode::*;
use crate::airs::casm::opcodes::jump_opcode::*;
use crate::airs::casm::opcodes::jump_opcode_test::*;
use crate::airs::casm::opcodes::ret_opcode::*;
use crate::airs::casm::opcodes::ret_opcode_test::*;
use crate::airs::felt252_id_memory::memory::*;

use crate::core::air_fn_registry::*;
use crate::core::expressions::felt252_expr::*;
use crate::core::expressions::felt_expr::*;
use crate::core::variables::*;

use crate::utils::test_utils::*;

// Macros
use crate::const_expr;
use crate::const_felt252_expr;

#[test]
fn test_entry_json() {
    let (_, entry) = AirFnRegistry::new(&GenericOpcode::default());
    compare_json(
        &entry,
        &format!(
            "{}{}.json",
            TEST_JSONS_OPCODES_DIR,
            entry.name.to_lowercase()
        ),
    );
}

#[test]
fn test_generic_call() {
    let mut generic_opcode = GenericOpcode::default();
    let mut call_opcode = CallOpcode {
        is_rel: true,
        op1_base_fp: false,
        memory: Felt252IdMemory::default(),
    };

    // Register values at opcode start
    let [pc, ap, fp] = [50, 200, 150];
    let immediate = 299;

    // Fill memory
    let mut memory_values = vec![(
        const_expr!(pc),
        const_felt252_expr!(
            assemble_instruction(0, 1, 1, call_opcode.get_flags().into()) as u128,
            0
        ),
    )];
    memory_values.push((const_expr!(pc + 1), const_felt252_expr!(immediate)));
    memory_values.push((const_expr!(ap), const_felt252_expr!(fp as i64)));
    memory_values.push((const_expr!(ap + 1), const_felt252_expr!(pc as i64 + 2)));

    generic_opcode.memory = Felt252IdMemory::new_with_data(memory_values.clone());
    call_opcode.memory = Felt252IdMemory::new_with_data(memory_values);

    // Run air function
    let (mut registry, _) = AirFnRegistry::new(&generic_opcode);
    registry.add_entry(&call_opcode);
    let (state, output) = registry.run_air(
        &generic_opcode,
        CasmStateVar::new(const_expr!(pc), const_expr!(ap), const_expr!(fp)),
    );
    let (_, expected_output) = registry.run_air(
        &call_opcode,
        CasmStateVar::new(const_expr!(pc), const_expr!(ap), const_expr!(fp)),
    );

    // Check output
    assert_eq!(expected_output.calc(), output.calc());

    // Check state
    let expected_state = vec![
        (50, ""),
        (200, ""),
        (150, ""),
        (32768, "offset_0"),
        (32769, "offset_1"),
        (32769, "offset_2"),
        (0, "dst_base_fp"),
        (0, "op0_base_fp"),
        (1, "op1_imm"),
        (0, "op1_base_fp"),
        (0, "op1_base_ap"),
        (0, "res_add"),
        (0, "res_mul"),
        (0, "pc_update_jump"),
        (1, "pc_update_jump_rel"),
        (0, "pc_update_jnz"),
        (0, "ap_update_add"),
        (0, "ap_update_add_1"),
        (1, "opcode_call"),
        (0, "opcode_ret"),
        (0, "opcode_assert_eq"),
        (2, "id"),
        (150, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (3, "id"),
        (52, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (1, "id"),
        (299, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (351, "add_res_limb_0"),
        (0, "add_res_limb_1"),
        (0, "add_res_limb_2"),
        (0, "add_res_limb_3"),
        (0, "add_res_limb_4"),
        (0, "add_res_limb_5"),
        (0, "add_res_limb_6"),
        (0, "add_res_limb_7"),
        (0, "add_res_limb_8"),
        (0, "add_res_limb_9"),
        (0, "add_res_limb_10"),
        (0, "add_res_limb_11"),
        (0, "add_res_limb_12"),
        (0, "add_res_limb_13"),
        (0, "add_res_limb_14"),
        (0, "add_res_limb_15"),
        (0, "add_res_limb_16"),
        (0, "add_res_limb_17"),
        (0, "add_res_limb_18"),
        (0, "add_res_limb_19"),
        (0, "add_res_limb_20"),
        (0, "add_res_limb_21"),
        (0, "add_res_limb_22"),
        (0, "add_res_limb_23"),
        (0, "add_res_limb_24"),
        (0, "add_res_limb_25"),
        (0, "add_res_limb_26"),
        (0, "add_res_limb_27"),
        (0, "sub_p_bit"),
        (188, "mul_res_limb_0"),
        (30, "mul_res_limb_1"),
        (0, "mul_res_limb_2"),
        (0, "mul_res_limb_3"),
        (0, "mul_res_limb_4"),
        (0, "mul_res_limb_5"),
        (0, "mul_res_limb_6"),
        (0, "mul_res_limb_7"),
        (0, "mul_res_limb_8"),
        (0, "mul_res_limb_9"),
        (0, "mul_res_limb_10"),
        (0, "mul_res_limb_11"),
        (0, "mul_res_limb_12"),
        (0, "mul_res_limb_13"),
        (0, "mul_res_limb_14"),
        (0, "mul_res_limb_15"),
        (0, "mul_res_limb_16"),
        (0, "mul_res_limb_17"),
        (0, "mul_res_limb_18"),
        (0, "mul_res_limb_19"),
        (0, "mul_res_limb_20"),
        (0, "mul_res_limb_21"),
        (0, "mul_res_limb_22"),
        (0, "mul_res_limb_23"),
        (0, "mul_res_limb_24"),
        (0, "mul_res_limb_25"),
        (0, "mul_res_limb_26"),
        (0, "mul_res_limb_27"),
        (0, "k"),
        (960, "carry_0"),
        (30, "carry_1"),
        (0, "carry_2"),
        (0, "carry_3"),
        (0, "carry_4"),
        (0, "carry_5"),
        (0, "carry_6"),
        (60, "carry_7"),
        (0, "carry_8"),
        (0, "carry_9"),
        (0, "carry_10"),
        (0, "carry_11"),
        (0, "carry_12"),
        (0, "carry_13"),
        (0, "carry_14"),
        (0, "carry_15"),
        (0, "carry_16"),
        (0, "carry_17"),
        (0, "carry_18"),
        (0, "carry_19"),
        (0, "carry_20"),
        (0, "carry_21"),
        (0, "carry_22"),
        (0, "carry_23"),
        (0, "carry_24"),
        (0, "carry_25"),
        (0, "carry_26"),
        (299, "res_limb_0"),
        (0, "res_limb_1"),
        (0, "res_limb_2"),
        (0, "res_limb_3"),
        (0, "res_limb_4"),
        (0, "res_limb_5"),
        (0, "res_limb_6"),
        (0, "res_limb_7"),
        (0, "res_limb_8"),
        (0, "res_limb_9"),
        (0, "res_limb_10"),
        (0, "res_limb_11"),
        (0, "res_limb_12"),
        (0, "res_limb_13"),
        (0, "res_limb_14"),
        (0, "res_limb_15"),
        (0, "res_limb_16"),
        (0, "res_limb_17"),
        (0, "res_limb_18"),
        (0, "res_limb_19"),
        (0, "res_limb_20"),
        (0, "res_limb_21"),
        (0, "res_limb_22"),
        (0, "res_limb_23"),
        (0, "res_limb_24"),
        (0, "res_limb_25"),
        (0, "res_limb_26"),
        (0, "res_limb_27"),
        (0, "msb"),
        (0, "mid_limbs_set"),
        (1285643938, "dst_sum_squares_inv"),
        (243381480, "dst_sum_inv"),
        (0, "op1_as_rel_imm_cond"),
        (0, "msb"),
        (0, "mid_limbs_set"),
        (349, "next_pc_jnz"),
    ]
    .into();
    assert!(
        state == expected_state,
        "State {} does not match {}",
        state,
        expected_state
    );
}

#[test]
fn test_generic_ret() {
    let mut generic_opcode = GenericOpcode::default();
    let mut ret_opcode = RetOpcode {
        memory: Felt252IdMemory::default(),
    };
    // Register values at opcode start
    let [pc, ap, fp] = [3, 11, 6];

    // Old values of pc, fp saved by the last call opcode
    let saved_fp = 4;
    let saved_pc = 1;

    // Fill memory
    let memory_values = vec![
        (
            const_expr!(pc),
            const_felt252_expr!(assemble_ret() as u128, 0),
        ),
        (const_expr!(fp - 1), const_felt252_expr!(saved_pc)),
        (const_expr!(fp - 2), const_felt252_expr!(saved_fp)),
    ];
    generic_opcode.memory = Felt252IdMemory::new_with_data(memory_values.clone());
    ret_opcode.memory = Felt252IdMemory::new_with_data(memory_values);

    // Run air function
    let (mut registry, _) = AirFnRegistry::new(&generic_opcode);
    registry.add_entry(&ret_opcode);
    let (state, output) = registry.run_air(
        &generic_opcode,
        CasmStateVar::new(const_expr!(pc), const_expr!(ap), const_expr!(fp)),
    );
    let (_, expected_output) = registry.run_air(
        &ret_opcode,
        CasmStateVar::new(const_expr!(pc), const_expr!(ap), const_expr!(fp)),
    );

    // Check output
    assert_eq!(expected_output.calc(), output.calc());

    // Check state
    let expected_state = vec![
        (3, ""),
        (11, ""),
        (6, ""),
        (32766, "offset_0"),
        (32767, "offset_1"),
        (32767, "offset_2"),
        (1, "dst_base_fp"),
        (1, "op0_base_fp"),
        (0, "op1_imm"),
        (1, "op1_base_fp"),
        (0, "op1_base_ap"),
        (0, "res_add"),
        (0, "res_mul"),
        (1, "pc_update_jump"),
        (0, "pc_update_jump_rel"),
        (0, "pc_update_jnz"),
        (0, "ap_update_add"),
        (0, "ap_update_add_1"),
        (0, "opcode_call"),
        (1, "opcode_ret"),
        (0, "opcode_assert_eq"),
        (2, "id"),
        (4, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (1, "id"),
        (1, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (1, "id"),
        (1, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (2, "add_res_limb_0"),
        (0, "add_res_limb_1"),
        (0, "add_res_limb_2"),
        (0, "add_res_limb_3"),
        (0, "add_res_limb_4"),
        (0, "add_res_limb_5"),
        (0, "add_res_limb_6"),
        (0, "add_res_limb_7"),
        (0, "add_res_limb_8"),
        (0, "add_res_limb_9"),
        (0, "add_res_limb_10"),
        (0, "add_res_limb_11"),
        (0, "add_res_limb_12"),
        (0, "add_res_limb_13"),
        (0, "add_res_limb_14"),
        (0, "add_res_limb_15"),
        (0, "add_res_limb_16"),
        (0, "add_res_limb_17"),
        (0, "add_res_limb_18"),
        (0, "add_res_limb_19"),
        (0, "add_res_limb_20"),
        (0, "add_res_limb_21"),
        (0, "add_res_limb_22"),
        (0, "add_res_limb_23"),
        (0, "add_res_limb_24"),
        (0, "add_res_limb_25"),
        (0, "add_res_limb_26"),
        (0, "add_res_limb_27"),
        (0, "sub_p_bit"),
        (1, "mul_res_limb_0"),
        (0, "mul_res_limb_1"),
        (0, "mul_res_limb_2"),
        (0, "mul_res_limb_3"),
        (0, "mul_res_limb_4"),
        (0, "mul_res_limb_5"),
        (0, "mul_res_limb_6"),
        (0, "mul_res_limb_7"),
        (0, "mul_res_limb_8"),
        (0, "mul_res_limb_9"),
        (0, "mul_res_limb_10"),
        (0, "mul_res_limb_11"),
        (0, "mul_res_limb_12"),
        (0, "mul_res_limb_13"),
        (0, "mul_res_limb_14"),
        (0, "mul_res_limb_15"),
        (0, "mul_res_limb_16"),
        (0, "mul_res_limb_17"),
        (0, "mul_res_limb_18"),
        (0, "mul_res_limb_19"),
        (0, "mul_res_limb_20"),
        (0, "mul_res_limb_21"),
        (0, "mul_res_limb_22"),
        (0, "mul_res_limb_23"),
        (0, "mul_res_limb_24"),
        (0, "mul_res_limb_25"),
        (0, "mul_res_limb_26"),
        (0, "mul_res_limb_27"),
        (0, "k"),
        (0, "carry_0"),
        (0, "carry_1"),
        (0, "carry_2"),
        (0, "carry_3"),
        (0, "carry_4"),
        (0, "carry_5"),
        (0, "carry_6"),
        (0, "carry_7"),
        (0, "carry_8"),
        (0, "carry_9"),
        (0, "carry_10"),
        (0, "carry_11"),
        (0, "carry_12"),
        (0, "carry_13"),
        (0, "carry_14"),
        (0, "carry_15"),
        (0, "carry_16"),
        (0, "carry_17"),
        (0, "carry_18"),
        (0, "carry_19"),
        (0, "carry_20"),
        (0, "carry_21"),
        (0, "carry_22"),
        (0, "carry_23"),
        (0, "carry_24"),
        (0, "carry_25"),
        (0, "carry_26"),
        (1, "res_limb_0"),
        (0, "res_limb_1"),
        (0, "res_limb_2"),
        (0, "res_limb_3"),
        (0, "res_limb_4"),
        (0, "res_limb_5"),
        (0, "res_limb_6"),
        (0, "res_limb_7"),
        (0, "res_limb_8"),
        (0, "res_limb_9"),
        (0, "res_limb_10"),
        (0, "res_limb_11"),
        (0, "res_limb_12"),
        (0, "res_limb_13"),
        (0, "res_limb_14"),
        (0, "res_limb_15"),
        (0, "res_limb_16"),
        (0, "res_limb_17"),
        (0, "res_limb_18"),
        (0, "res_limb_19"),
        (0, "res_limb_20"),
        (0, "res_limb_21"),
        (0, "res_limb_22"),
        (0, "res_limb_23"),
        (0, "res_limb_24"),
        (0, "res_limb_25"),
        (0, "res_limb_26"),
        (0, "res_limb_27"),
        (0, "msb"),
        (0, "mid_limbs_set"),
        (2029429668, "dst_sum_squares_inv"),
        (536870912, "dst_sum_inv"),
        (0, "op1_as_rel_imm_cond"),
        (0, "msb"),
        (0, "mid_limbs_set"),
        (4, "next_pc_jnz"),
    ]
    .into();
    assert!(
        state == expected_state,
        "State {} does not match {}",
        state,
        expected_state
    );
}

#[test]
fn test_generic_assert_equal() {
    let mut generic_opcode = GenericOpcode::default();
    let mut assert_equal_opcode = AssertEqOpcode {
        is_double_deref: false,
        is_imm: false,
        memory: Felt252IdMemory::default(),
    };
    let [offset0, offset1, offset2] = [3, -1, 2];
    let dst = 3;
    let op1 = 3;

    // Register values at opcode start
    let [pc, ap, fp] = [3, 11, 6];

    // Fill memory
    let mut memory_values = vec![(
        const_expr!(pc),
        const_felt252_expr!(
            assemble_instruction(
                offset0,
                offset1,
                offset2,
                assert_equal_opcode
                    .get_flags()
                    .non_constants_to_arr(&[false, true, false, false]),
            ) as u128,
            0
        ),
    )];
    memory_values.push((
        const_expr!((ap as i16 + offset0) as u32),
        const_felt252_expr!(dst as i128),
    ));
    memory_values.push((
        const_expr!((fp as i16 + offset2) as u32),
        const_felt252_expr!(op1 as i128),
    ));
    // Not in use
    memory_values.push((
        const_expr!((fp as i16 + offset1) as u32),
        const_felt252_expr!(0, 0),
    ));
    generic_opcode.memory = Felt252IdMemory::new_with_data(memory_values.clone());
    assert_equal_opcode.memory = Felt252IdMemory::new_with_data(memory_values);

    // Run air function
    let (mut registry, _) = AirFnRegistry::new(&generic_opcode);
    registry.add_entry(&assert_equal_opcode);
    let (state, output) = registry.run_air(
        &generic_opcode,
        CasmStateVar::new(const_expr!(pc), const_expr!(ap), const_expr!(fp)),
    );
    let (_, expected_output) = registry.run_air(
        &assert_equal_opcode,
        CasmStateVar::new(const_expr!(pc), const_expr!(ap), const_expr!(fp)),
    );

    // Check output
    assert_eq!(expected_output.calc(), output.calc());

    // Check state
    let expected_state = vec![
        (3, ""),
        (11, ""),
        (6, ""),
        (32771, "offset_0"),
        (32767, "offset_1"),
        (32770, "offset_2"),
        (0, "dst_base_fp"),
        (1, "op0_base_fp"),
        (0, "op1_imm"),
        (1, "op1_base_fp"),
        (0, "op1_base_ap"),
        (0, "res_add"),
        (0, "res_mul"),
        (0, "pc_update_jump"),
        (0, "pc_update_jump_rel"),
        (0, "pc_update_jnz"),
        (0, "ap_update_add"),
        (0, "ap_update_add_1"),
        (0, "opcode_call"),
        (0, "opcode_ret"),
        (1, "opcode_assert_eq"),
        (1, "id"),
        (3, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (2, "id"),
        (0, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (1, "id"),
        (3, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (3, "add_res_limb_0"),
        (0, "add_res_limb_1"),
        (0, "add_res_limb_2"),
        (0, "add_res_limb_3"),
        (0, "add_res_limb_4"),
        (0, "add_res_limb_5"),
        (0, "add_res_limb_6"),
        (0, "add_res_limb_7"),
        (0, "add_res_limb_8"),
        (0, "add_res_limb_9"),
        (0, "add_res_limb_10"),
        (0, "add_res_limb_11"),
        (0, "add_res_limb_12"),
        (0, "add_res_limb_13"),
        (0, "add_res_limb_14"),
        (0, "add_res_limb_15"),
        (0, "add_res_limb_16"),
        (0, "add_res_limb_17"),
        (0, "add_res_limb_18"),
        (0, "add_res_limb_19"),
        (0, "add_res_limb_20"),
        (0, "add_res_limb_21"),
        (0, "add_res_limb_22"),
        (0, "add_res_limb_23"),
        (0, "add_res_limb_24"),
        (0, "add_res_limb_25"),
        (0, "add_res_limb_26"),
        (0, "add_res_limb_27"),
        (0, "sub_p_bit"),
        (0, "mul_res_limb_0"),
        (0, "mul_res_limb_1"),
        (0, "mul_res_limb_2"),
        (0, "mul_res_limb_3"),
        (0, "mul_res_limb_4"),
        (0, "mul_res_limb_5"),
        (0, "mul_res_limb_6"),
        (0, "mul_res_limb_7"),
        (0, "mul_res_limb_8"),
        (0, "mul_res_limb_9"),
        (0, "mul_res_limb_10"),
        (0, "mul_res_limb_11"),
        (0, "mul_res_limb_12"),
        (0, "mul_res_limb_13"),
        (0, "mul_res_limb_14"),
        (0, "mul_res_limb_15"),
        (0, "mul_res_limb_16"),
        (0, "mul_res_limb_17"),
        (0, "mul_res_limb_18"),
        (0, "mul_res_limb_19"),
        (0, "mul_res_limb_20"),
        (0, "mul_res_limb_21"),
        (0, "mul_res_limb_22"),
        (0, "mul_res_limb_23"),
        (0, "mul_res_limb_24"),
        (0, "mul_res_limb_25"),
        (0, "mul_res_limb_26"),
        (0, "mul_res_limb_27"),
        (0, "k"),
        (0, "carry_0"),
        (0, "carry_1"),
        (0, "carry_2"),
        (0, "carry_3"),
        (0, "carry_4"),
        (0, "carry_5"),
        (0, "carry_6"),
        (0, "carry_7"),
        (0, "carry_8"),
        (0, "carry_9"),
        (0, "carry_10"),
        (0, "carry_11"),
        (0, "carry_12"),
        (0, "carry_13"),
        (0, "carry_14"),
        (0, "carry_15"),
        (0, "carry_16"),
        (0, "carry_17"),
        (0, "carry_18"),
        (0, "carry_19"),
        (0, "carry_20"),
        (0, "carry_21"),
        (0, "carry_22"),
        (0, "carry_23"),
        (0, "carry_24"),
        (0, "carry_25"),
        (0, "carry_26"),
        (3, "res_limb_0"),
        (0, "res_limb_1"),
        (0, "res_limb_2"),
        (0, "res_limb_3"),
        (0, "res_limb_4"),
        (0, "res_limb_5"),
        (0, "res_limb_6"),
        (0, "res_limb_7"),
        (0, "res_limb_8"),
        (0, "res_limb_9"),
        (0, "res_limb_10"),
        (0, "res_limb_11"),
        (0, "res_limb_12"),
        (0, "res_limb_13"),
        (0, "res_limb_14"),
        (0, "res_limb_15"),
        (0, "res_limb_16"),
        (0, "res_limb_17"),
        (0, "res_limb_18"),
        (0, "res_limb_19"),
        (0, "res_limb_20"),
        (0, "res_limb_21"),
        (0, "res_limb_22"),
        (0, "res_limb_23"),
        (0, "res_limb_24"),
        (0, "res_limb_25"),
        (0, "res_limb_26"),
        (0, "res_limb_27"),
        (0, "msb"),
        (0, "mid_limbs_set"),
        (60231555, "dst_sum_squares_inv"),
        (1431655765, "dst_sum_inv"),
        (0, "op1_as_rel_imm_cond"),
        (0, "msb"),
        (0, "mid_limbs_set"),
        (6, "next_pc_jnz"),
    ]
    .into();
    assert!(
        state == expected_state,
        "State {} does not match {}",
        state,
        expected_state
    );
}

#[test]
fn test_generic_jump() {
    let mut generic_opcode = GenericOpcode::default();
    let mut jump_opcode = JumpOpcode {
        is_rel: false,
        is_imm: false,
        is_double_deref: false,
        memory: Felt252IdMemory::default(),
    };

    let offset_value = 10;
    let op1 = 5;

    // Register values at opcode start
    let [pc, ap, fp] = [3, 11, 6];

    // Fill memory
    let mut memory_values = vec![(
        const_expr!(pc),
        const_felt252_expr!(
            assemble_jump(
                None,
                Some(offset_value),
                jump_opcode
                    .get_flags()
                    .non_constants_to_arr(&[true, false, false]),
            ) as u128,
            0
        ),
    )];
    memory_values.push((
        const_expr!((fp as i16 + offset_value) as u32),
        const_felt252_expr!(op1 as i128),
    ));
    // Not in use
    memory_values.push((
        const_expr!((fp as i64 - 1) as u32),
        const_felt252_expr!(0, 0),
    ));
    generic_opcode.memory = Felt252IdMemory::new_with_data(memory_values.clone());
    jump_opcode.memory = Felt252IdMemory::new_with_data(memory_values);

    // Run air function
    let (mut registry, _) = AirFnRegistry::new(&generic_opcode);
    registry.add_entry(&jump_opcode);
    let (state, output) = registry.run_air(
        &generic_opcode,
        CasmStateVar::new(const_expr!(pc), const_expr!(ap), const_expr!(fp)),
    );
    let (_, expected_output) = registry.run_air(
        &jump_opcode,
        CasmStateVar::new(const_expr!(pc), const_expr!(ap), const_expr!(fp)),
    );

    // Check output
    assert_eq!(expected_output.calc(), output.calc());

    // Check state
    let expected_state = vec![
        (3, ""),
        (11, ""),
        (6, ""),
        (32767, "offset_0"),
        (32767, "offset_1"),
        (32778, "offset_2"),
        (1, "dst_base_fp"),
        (1, "op0_base_fp"),
        (0, "op1_imm"),
        (1, "op1_base_fp"),
        (0, "op1_base_ap"),
        (0, "res_add"),
        (0, "res_mul"),
        (1, "pc_update_jump"),
        (0, "pc_update_jump_rel"),
        (0, "pc_update_jnz"),
        (0, "ap_update_add"),
        (0, "ap_update_add_1"),
        (0, "opcode_call"),
        (0, "opcode_ret"),
        (0, "opcode_assert_eq"),
        (2, "id"),
        (0, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (2, "id"),
        (0, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (1, "id"),
        (5, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (5, "add_res_limb_0"),
        (0, "add_res_limb_1"),
        (0, "add_res_limb_2"),
        (0, "add_res_limb_3"),
        (0, "add_res_limb_4"),
        (0, "add_res_limb_5"),
        (0, "add_res_limb_6"),
        (0, "add_res_limb_7"),
        (0, "add_res_limb_8"),
        (0, "add_res_limb_9"),
        (0, "add_res_limb_10"),
        (0, "add_res_limb_11"),
        (0, "add_res_limb_12"),
        (0, "add_res_limb_13"),
        (0, "add_res_limb_14"),
        (0, "add_res_limb_15"),
        (0, "add_res_limb_16"),
        (0, "add_res_limb_17"),
        (0, "add_res_limb_18"),
        (0, "add_res_limb_19"),
        (0, "add_res_limb_20"),
        (0, "add_res_limb_21"),
        (0, "add_res_limb_22"),
        (0, "add_res_limb_23"),
        (0, "add_res_limb_24"),
        (0, "add_res_limb_25"),
        (0, "add_res_limb_26"),
        (0, "add_res_limb_27"),
        (0, "sub_p_bit"),
        (0, "mul_res_limb_0"),
        (0, "mul_res_limb_1"),
        (0, "mul_res_limb_2"),
        (0, "mul_res_limb_3"),
        (0, "mul_res_limb_4"),
        (0, "mul_res_limb_5"),
        (0, "mul_res_limb_6"),
        (0, "mul_res_limb_7"),
        (0, "mul_res_limb_8"),
        (0, "mul_res_limb_9"),
        (0, "mul_res_limb_10"),
        (0, "mul_res_limb_11"),
        (0, "mul_res_limb_12"),
        (0, "mul_res_limb_13"),
        (0, "mul_res_limb_14"),
        (0, "mul_res_limb_15"),
        (0, "mul_res_limb_16"),
        (0, "mul_res_limb_17"),
        (0, "mul_res_limb_18"),
        (0, "mul_res_limb_19"),
        (0, "mul_res_limb_20"),
        (0, "mul_res_limb_21"),
        (0, "mul_res_limb_22"),
        (0, "mul_res_limb_23"),
        (0, "mul_res_limb_24"),
        (0, "mul_res_limb_25"),
        (0, "mul_res_limb_26"),
        (0, "mul_res_limb_27"),
        (0, "k"),
        (0, "carry_0"),
        (0, "carry_1"),
        (0, "carry_2"),
        (0, "carry_3"),
        (0, "carry_4"),
        (0, "carry_5"),
        (0, "carry_6"),
        (0, "carry_7"),
        (0, "carry_8"),
        (0, "carry_9"),
        (0, "carry_10"),
        (0, "carry_11"),
        (0, "carry_12"),
        (0, "carry_13"),
        (0, "carry_14"),
        (0, "carry_15"),
        (0, "carry_16"),
        (0, "carry_17"),
        (0, "carry_18"),
        (0, "carry_19"),
        (0, "carry_20"),
        (0, "carry_21"),
        (0, "carry_22"),
        (0, "carry_23"),
        (0, "carry_24"),
        (0, "carry_25"),
        (0, "carry_26"),
        (5, "res_limb_0"),
        (0, "res_limb_1"),
        (0, "res_limb_2"),
        (0, "res_limb_3"),
        (0, "res_limb_4"),
        (0, "res_limb_5"),
        (0, "res_limb_6"),
        (0, "res_limb_7"),
        (0, "res_limb_8"),
        (0, "res_limb_9"),
        (0, "res_limb_10"),
        (0, "res_limb_11"),
        (0, "res_limb_12"),
        (0, "res_limb_13"),
        (0, "res_limb_14"),
        (0, "res_limb_15"),
        (0, "res_limb_16"),
        (0, "res_limb_17"),
        (0, "res_limb_18"),
        (0, "res_limb_19"),
        (0, "res_limb_20"),
        (0, "res_limb_21"),
        (0, "res_limb_22"),
        (0, "res_limb_23"),
        (0, "res_limb_24"),
        (0, "res_limb_25"),
        (0, "res_limb_26"),
        (0, "res_limb_27"),
        (0, "msb"),
        (0, "mid_limbs_set"),
        (1351207863, "dst_sum_squares_inv"),
        (1, "dst_sum_inv"),
        (0, "op1_as_rel_imm_cond"),
        (0, "msb"),
        (0, "mid_limbs_set"),
        (4, "next_pc_jnz"),
    ]
    .into();
    assert!(
        state == expected_state,
        "State {} does not match {}",
        state,
        expected_state
    );
}

#[test]
fn test_generic_jump_not_zero_taken() {
    let mut generic_opcode = GenericOpcode::default();
    let mut jnz_opcode = JnzOpcode {
        is_taken: true,
        dst_base_fp: false,
        memory: Felt252IdMemory::default(),
    };

    // Register values at opcode start
    let [pc, ap, fp] = [50, 200, 150];
    let offset_dst = -13;
    let op1 = 15;

    // Fill memory
    let mut memory_values = vec![(
        const_expr!(pc),
        const_felt252_expr!(
            assemble_instruction(
                offset_dst,
                -1,
                1,
                jnz_opcode.get_flags().non_constants_to_arr(&[false])
            ) as u128,
            0
        ),
    )];
    memory_values.push((const_expr!(pc + 1), const_felt252_expr!(op1 as i128)));
    memory_values.push((
        const_expr!((ap as i16 + offset_dst) as u32),
        const_felt252_expr!(123, 456),
    ));
    // Not in use
    memory_values.push((const_expr!(fp - 1), const_felt252_expr!(0, 0)));
    generic_opcode.memory = Felt252IdMemory::new_with_data(memory_values.clone());
    jnz_opcode.memory = Felt252IdMemory::new_with_data(memory_values);

    // Run air function
    let (mut registry, _) = AirFnRegistry::new(&generic_opcode);
    registry.add_entry(&jnz_opcode);
    let (state, output) = registry.run_air(
        &generic_opcode,
        CasmStateVar::new(const_expr!(pc), const_expr!(ap), const_expr!(fp)),
    );
    let (_, expected_output) = registry.run_air(
        &jnz_opcode,
        CasmStateVar::new(const_expr!(pc), const_expr!(ap), const_expr!(fp)),
    );

    // Check output
    assert_eq!(expected_output.calc(), output.calc());

    // Check state
    let expected_state = vec![
        (50, ""),
        (200, ""),
        (150, ""),
        (32755, "offset_0"),
        (32767, "offset_1"),
        (32769, "offset_2"),
        (0, "dst_base_fp"),
        (1, "op0_base_fp"),
        (1, "op1_imm"),
        (0, "op1_base_fp"),
        (0, "op1_base_ap"),
        (0, "res_add"),
        (0, "res_mul"),
        (0, "pc_update_jump"),
        (0, "pc_update_jump_rel"),
        (1, "pc_update_jnz"),
        (0, "ap_update_add"),
        (0, "ap_update_add_1"),
        (0, "opcode_call"),
        (0, "opcode_ret"),
        (0, "opcode_assert_eq"),
        (2, "id"),
        (123, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (288, "limb_14"),
        (3, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (3, "id"),
        (0, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (1, "id"),
        (15, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (15, "add_res_limb_0"),
        (0, "add_res_limb_1"),
        (0, "add_res_limb_2"),
        (0, "add_res_limb_3"),
        (0, "add_res_limb_4"),
        (0, "add_res_limb_5"),
        (0, "add_res_limb_6"),
        (0, "add_res_limb_7"),
        (0, "add_res_limb_8"),
        (0, "add_res_limb_9"),
        (0, "add_res_limb_10"),
        (0, "add_res_limb_11"),
        (0, "add_res_limb_12"),
        (0, "add_res_limb_13"),
        (0, "add_res_limb_14"),
        (0, "add_res_limb_15"),
        (0, "add_res_limb_16"),
        (0, "add_res_limb_17"),
        (0, "add_res_limb_18"),
        (0, "add_res_limb_19"),
        (0, "add_res_limb_20"),
        (0, "add_res_limb_21"),
        (0, "add_res_limb_22"),
        (0, "add_res_limb_23"),
        (0, "add_res_limb_24"),
        (0, "add_res_limb_25"),
        (0, "add_res_limb_26"),
        (0, "add_res_limb_27"),
        (0, "sub_p_bit"),
        (0, "mul_res_limb_0"),
        (0, "mul_res_limb_1"),
        (0, "mul_res_limb_2"),
        (0, "mul_res_limb_3"),
        (0, "mul_res_limb_4"),
        (0, "mul_res_limb_5"),
        (0, "mul_res_limb_6"),
        (0, "mul_res_limb_7"),
        (0, "mul_res_limb_8"),
        (0, "mul_res_limb_9"),
        (0, "mul_res_limb_10"),
        (0, "mul_res_limb_11"),
        (0, "mul_res_limb_12"),
        (0, "mul_res_limb_13"),
        (0, "mul_res_limb_14"),
        (0, "mul_res_limb_15"),
        (0, "mul_res_limb_16"),
        (0, "mul_res_limb_17"),
        (0, "mul_res_limb_18"),
        (0, "mul_res_limb_19"),
        (0, "mul_res_limb_20"),
        (0, "mul_res_limb_21"),
        (0, "mul_res_limb_22"),
        (0, "mul_res_limb_23"),
        (0, "mul_res_limb_24"),
        (0, "mul_res_limb_25"),
        (0, "mul_res_limb_26"),
        (0, "mul_res_limb_27"),
        (0, "k"),
        (0, "carry_0"),
        (0, "carry_1"),
        (0, "carry_2"),
        (0, "carry_3"),
        (0, "carry_4"),
        (0, "carry_5"),
        (0, "carry_6"),
        (0, "carry_7"),
        (0, "carry_8"),
        (0, "carry_9"),
        (0, "carry_10"),
        (0, "carry_11"),
        (0, "carry_12"),
        (0, "carry_13"),
        (0, "carry_14"),
        (0, "carry_15"),
        (0, "carry_16"),
        (0, "carry_17"),
        (0, "carry_18"),
        (0, "carry_19"),
        (0, "carry_20"),
        (0, "carry_21"),
        (0, "carry_22"),
        (0, "carry_23"),
        (0, "carry_24"),
        (0, "carry_25"),
        (0, "carry_26"),
        (0, "res_limb_0"),
        (0, "res_limb_1"),
        (0, "res_limb_2"),
        (0, "res_limb_3"),
        (0, "res_limb_4"),
        (0, "res_limb_5"),
        (0, "res_limb_6"),
        (0, "res_limb_7"),
        (0, "res_limb_8"),
        (0, "res_limb_9"),
        (0, "res_limb_10"),
        (0, "res_limb_11"),
        (0, "res_limb_12"),
        (0, "res_limb_13"),
        (0, "res_limb_14"),
        (0, "res_limb_15"),
        (0, "res_limb_16"),
        (0, "res_limb_17"),
        (0, "res_limb_18"),
        (0, "res_limb_19"),
        (0, "res_limb_20"),
        (0, "res_limb_21"),
        (0, "res_limb_22"),
        (0, "res_limb_23"),
        (0, "res_limb_24"),
        (0, "res_limb_25"),
        (0, "res_limb_26"),
        (0, "res_limb_27"),
        (0, "msb"),
        (0, "mid_limbs_set"),
        (500077285, "dst_sum_squares_inv"),
        (1955558780, "dst_sum_inv"),
        (414, "op1_as_rel_imm_cond"),
        (0, "msb"),
        (0, "mid_limbs_set"),
        (65, "next_pc_jnz"),
    ]
    .into();
    assert!(
        state == expected_state,
        "State {} does not match {}",
        state,
        expected_state
    );
}

#[test]
fn test_generic_jump_not_zero_not_taken() {
    let mut generic_opcode = GenericOpcode::default();
    let mut jnz_opcode = JnzOpcode {
        is_taken: false,
        dst_base_fp: false,
        memory: Felt252IdMemory::default(),
    };

    // Register values at opcode start
    let [pc, ap, fp] = [50, 200, 150];
    let offset_dst = -13;
    let op1 = 15;

    // Fill memory
    let mut memory_values = vec![(
        const_expr!(pc),
        const_felt252_expr!(
            assemble_instruction(
                offset_dst,
                -1,
                1,
                jnz_opcode.get_flags().non_constants_to_arr(&[false])
            ) as u128,
            0
        ),
    )];
    memory_values.push((const_expr!(pc + 1), const_felt252_expr!(op1 as i128)));
    memory_values.push((
        const_expr!((ap as i16 + offset_dst) as u32),
        const_felt252_expr!(0, 0),
    ));
    // Not in use
    memory_values.push((const_expr!(fp - 1), const_felt252_expr!(0, 0)));
    generic_opcode.memory = Felt252IdMemory::new_with_data(memory_values.clone());
    jnz_opcode.memory = Felt252IdMemory::new_with_data(memory_values);

    // Run air function
    let (mut registry, _) = AirFnRegistry::new(&generic_opcode);
    registry.add_entry(&jnz_opcode);
    let (state, output) = registry.run_air(
        &generic_opcode,
        CasmStateVar::new(const_expr!(pc), const_expr!(ap), const_expr!(fp)),
    );
    let (_, expected_output) = registry.run_air(
        &jnz_opcode,
        CasmStateVar::new(const_expr!(pc), const_expr!(ap), const_expr!(fp)),
    );

    // Check output
    assert_eq!(expected_output.calc(), output.calc());

    // Check state
    let expected_state = vec![
        (50, ""),
        (200, ""),
        (150, ""),
        (32755, "offset_0"),
        (32767, "offset_1"),
        (32769, "offset_2"),
        (0, "dst_base_fp"),
        (1, "op0_base_fp"),
        (1, "op1_imm"),
        (0, "op1_base_fp"),
        (0, "op1_base_ap"),
        (0, "res_add"),
        (0, "res_mul"),
        (0, "pc_update_jump"),
        (0, "pc_update_jump_rel"),
        (1, "pc_update_jnz"),
        (0, "ap_update_add"),
        (0, "ap_update_add_1"),
        (0, "opcode_call"),
        (0, "opcode_ret"),
        (0, "opcode_assert_eq"),
        (2, "id"),
        (0, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (2, "id"),
        (0, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (1, "id"),
        (15, "limb_0"),
        (0, "limb_1"),
        (0, "limb_2"),
        (0, "limb_3"),
        (0, "limb_4"),
        (0, "limb_5"),
        (0, "limb_6"),
        (0, "limb_7"),
        (0, "limb_8"),
        (0, "limb_9"),
        (0, "limb_10"),
        (0, "limb_11"),
        (0, "limb_12"),
        (0, "limb_13"),
        (0, "limb_14"),
        (0, "limb_15"),
        (0, "limb_16"),
        (0, "limb_17"),
        (0, "limb_18"),
        (0, "limb_19"),
        (0, "limb_20"),
        (0, "limb_21"),
        (0, "limb_22"),
        (0, "limb_23"),
        (0, "limb_24"),
        (0, "limb_25"),
        (0, "limb_26"),
        (0, "limb_27"),
        (15, "add_res_limb_0"),
        (0, "add_res_limb_1"),
        (0, "add_res_limb_2"),
        (0, "add_res_limb_3"),
        (0, "add_res_limb_4"),
        (0, "add_res_limb_5"),
        (0, "add_res_limb_6"),
        (0, "add_res_limb_7"),
        (0, "add_res_limb_8"),
        (0, "add_res_limb_9"),
        (0, "add_res_limb_10"),
        (0, "add_res_limb_11"),
        (0, "add_res_limb_12"),
        (0, "add_res_limb_13"),
        (0, "add_res_limb_14"),
        (0, "add_res_limb_15"),
        (0, "add_res_limb_16"),
        (0, "add_res_limb_17"),
        (0, "add_res_limb_18"),
        (0, "add_res_limb_19"),
        (0, "add_res_limb_20"),
        (0, "add_res_limb_21"),
        (0, "add_res_limb_22"),
        (0, "add_res_limb_23"),
        (0, "add_res_limb_24"),
        (0, "add_res_limb_25"),
        (0, "add_res_limb_26"),
        (0, "add_res_limb_27"),
        (0, "sub_p_bit"),
        (0, "mul_res_limb_0"),
        (0, "mul_res_limb_1"),
        (0, "mul_res_limb_2"),
        (0, "mul_res_limb_3"),
        (0, "mul_res_limb_4"),
        (0, "mul_res_limb_5"),
        (0, "mul_res_limb_6"),
        (0, "mul_res_limb_7"),
        (0, "mul_res_limb_8"),
        (0, "mul_res_limb_9"),
        (0, "mul_res_limb_10"),
        (0, "mul_res_limb_11"),
        (0, "mul_res_limb_12"),
        (0, "mul_res_limb_13"),
        (0, "mul_res_limb_14"),
        (0, "mul_res_limb_15"),
        (0, "mul_res_limb_16"),
        (0, "mul_res_limb_17"),
        (0, "mul_res_limb_18"),
        (0, "mul_res_limb_19"),
        (0, "mul_res_limb_20"),
        (0, "mul_res_limb_21"),
        (0, "mul_res_limb_22"),
        (0, "mul_res_limb_23"),
        (0, "mul_res_limb_24"),
        (0, "mul_res_limb_25"),
        (0, "mul_res_limb_26"),
        (0, "mul_res_limb_27"),
        (0, "k"),
        (0, "carry_0"),
        (0, "carry_1"),
        (0, "carry_2"),
        (0, "carry_3"),
        (0, "carry_4"),
        (0, "carry_5"),
        (0, "carry_6"),
        (0, "carry_7"),
        (0, "carry_8"),
        (0, "carry_9"),
        (0, "carry_10"),
        (0, "carry_11"),
        (0, "carry_12"),
        (0, "carry_13"),
        (0, "carry_14"),
        (0, "carry_15"),
        (0, "carry_16"),
        (0, "carry_17"),
        (0, "carry_18"),
        (0, "carry_19"),
        (0, "carry_20"),
        (0, "carry_21"),
        (0, "carry_22"),
        (0, "carry_23"),
        (0, "carry_24"),
        (0, "carry_25"),
        (0, "carry_26"),
        (0, "res_limb_0"),
        (0, "res_limb_1"),
        (0, "res_limb_2"),
        (0, "res_limb_3"),
        (0, "res_limb_4"),
        (0, "res_limb_5"),
        (0, "res_limb_6"),
        (0, "res_limb_7"),
        (0, "res_limb_8"),
        (0, "res_limb_9"),
        (0, "res_limb_10"),
        (0, "res_limb_11"),
        (0, "res_limb_12"),
        (0, "res_limb_13"),
        (0, "res_limb_14"),
        (0, "res_limb_15"),
        (0, "res_limb_16"),
        (0, "res_limb_17"),
        (0, "res_limb_18"),
        (0, "res_limb_19"),
        (0, "res_limb_20"),
        (0, "res_limb_21"),
        (0, "res_limb_22"),
        (0, "res_limb_23"),
        (0, "res_limb_24"),
        (0, "res_limb_25"),
        (0, "res_limb_26"),
        (0, "res_limb_27"),
        (0, "msb"),
        (0, "mid_limbs_set"),
        (1351207863, "dst_sum_squares_inv"),
        (1, "dst_sum_inv"),
        (0, "op1_as_rel_imm_cond"),
        (0, "msb"),
        (0, "mid_limbs_set"),
        (52, "next_pc_jnz"),
    ]
    .into();
    assert!(
        state == expected_state,
        "State {} does not match {}",
        state,
        expected_state
    );
}

#[test]
#[should_panic(expected = "0 has no inverse")]
fn test_generic_jump_not_zero_dst_is_p() {
    let mut generic_opcode = GenericOpcode::default();
    let jnz_opcode = JnzOpcode {
        is_taken: false,
        dst_base_fp: false,
        memory: Felt252IdMemory::default(),
    };

    // Register values at opcode start
    let [pc, ap, fp] = [50, 200, 150];
    let offset_dst = -13;
    let op1 = 15;

    // Fill memory
    let mut memory_values = vec![(
        const_expr!(pc),
        const_felt252_expr!(
            assemble_instruction(
                offset_dst,
                -1,
                1,
                jnz_opcode.get_flags().non_constants_to_arr(&[false])
            ) as u128,
            0
        ),
    )];
    memory_values.push((const_expr!(pc + 1), const_felt252_expr!(op1 as i128)));
    memory_values.push((
        const_expr!((ap as i16 + offset_dst) as u32),
        const_felt252_expr!(1, 10633823966279327296825105735305134080),
    ));
    // Not in use
    memory_values.push((const_expr!(fp - 1), const_felt252_expr!(0, 0)));
    generic_opcode.memory = Felt252IdMemory::new_with_data(memory_values);

    // Run air function
    let (registry, _) = AirFnRegistry::new(&generic_opcode);
    registry.run_air(
        &generic_opcode,
        CasmStateVar::new(const_expr!(pc), const_expr!(ap), const_expr!(fp)),
    );
}
