#!/usr/bin/python3

"""
A test to check that the autogenerated code compiles inside stwo-circuits. Should catch
mistakes such as missing imports in the autogenerated code.

The revision of stwo-circuits where the autogenerated code is supposed to compile is
taken from the file `supported-stwo-circuits-rev`.
"""

import os
import sys

script_dir = os.path.abspath(os.path.dirname(__file__))
sys.path.insert(0, script_dir)
from test_generated_code_common import run_cmd, clone_or_update_repo

# The revision of stwo-circuits where the autogenerated code is supposed to compile.
# Update scripts/supported-stwo-circuits-rev when changing generated code that targets stwo-circuits.
with open(os.path.join(script_dir, "supported-stwo-circuits-rev")) as f:
    STWO_CIRCUITS_COMMIT = f.read().strip()


repository_root = os.path.join(script_dir, "..")
clone_dir = os.path.join(repository_root, "build", "stwo-circuits")

print(f"Testing against stwo-circuits commit {STWO_CIRCUITS_COMMIT}")

clone_or_update_repo('https://github.com/starkware-libs/stwo-circuits', clone_dir, STWO_CIRCUITS_COMMIT)

# Generate code
run_cmd(['cargo', 'run', '--bin', 'cairo_code_gen', '--', 'generate-stwo-circuits',
         '--source', os.path.join(repository_root),
         '--stwo-circuits-path', clone_dir])

# Test generated Rust code
os.chdir(clone_dir)
cargo_test_return_code = run_cmd(['cargo', 'test'], check_success=False)
if cargo_test_return_code != 0:
    print(f"Failure: cargo test in stwo-circuits exited with {cargo_test_return_code}")
    exit(1)

print("Success!")
exit(0)
