#!/usr/bin/python3

"""
Checks that freshly autogenerated files are equal to the ones committed in HEAD.
"""

import os
import sys
import subprocess
import argparse


def check_autogen_code(codegen_command: str, repository_root: str):
    # Generate code.
    subprocess.run(
        [
            "cargo",
            "run",
            "--bin",
            "air_code_gen",
            "--",
            codegen_command,
            "--root-dir",
            repository_root,
        ],
        check=True,
    )

    # Check if the generated code is equal to the committed code.
    result = subprocess.run(
        ["git", "-C", f"{repository_root}", "status", "--porcelain"],
        # Don't capture stderr.
        stdout=subprocess.PIPE,
        text=True,
        check=True,
    )

    assert not result.stdout, (
        f"Code generation introduced diffs in these files: {result.stdout}"
    )
    print("Success! The committed autogenerated files are up-to-date.")


if __name__ == "__main__":
    script_dir = os.path.abspath(os.path.dirname(__file__))
    repository_root = os.path.join(script_dir, "..")

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "command", choices=["generate-stwo-cairo", "generate-stwo-circuits"]
    )
    args = parser.parse_args()

    # Generate the code and panic if the generated code is not equal to the committed code.
    check_autogen_code(args.command, repository_root)
