#!/usr/bin/python3

"""
A test to check that the autogenerated code compiles inside stwo-cairo. Should catch
mistakes such as missing imports in the autogenerated code.

The revision of stwo-cairo where the autogenerated code is supposed to compile is
taken from the file `supported-stwo-cairo-rev` file.
"""

import subprocess
import re
import os

def run_cmd(args, check_success=True):
    print(f"Running {args}")
    return_code = subprocess.call(args)
    if check_success:
        assert return_code == 0, f"Command exited with {return_code}"
    return return_code

script_dir = os.path.abspath(os.path.dirname(__file__))
repository_root = os.path.join(script_dir, "..")
clone_dir = os.path.join(repository_root, "build", "stwo-cairo")

stwo_cairo_commit = open(os.path.join(repository_root, "supported-stwo-cairo-rev")).read().strip()
assert re.match("[0-9a-f]{40}", stwo_cairo_commit), "supported-stwo-cairo-rev doesn't contain a valid commit hash"
print(f"Testing against stwo commit {stwo_cairo_commit}")

if not os.path.exists(clone_dir):
    # Clone stwo-cairo
    run_cmd(['git', 'clone', '--depth=1', 'https://github.com/starkware-libs/stwo-cairo', clone_dir])
else:
    # Use the existing stwo-cairo clone
    run_cmd(['git', '-C', clone_dir, 'reset', '--hard'])

# Checkout the required revision
run_cmd(['git', '-C', clone_dir, 'fetch', '--depth=1', 'origin', stwo_cairo_commit])
run_cmd(['git', '-C', clone_dir, 'checkout', stwo_cairo_commit])

# Generate code
run_cmd(['cargo', 'run', '--bin', 'cairo_code_gen', '--',
         '--source', os.path.join(repository_root, 'crates/compiled_casm_air/src/compiled_jsons'),
         '--rust-constraints-dest', os.path.join(clone_dir, 'stwo_cairo_prover/crates/cairo-air/src/components'),
         '--cairo-constraints-dest', os.path.join(clone_dir, 'stwo_cairo_verifier/crates/cairo-air/src/components'),
         '--witness-dest', os.path.join(clone_dir, 'stwo_cairo_prover/crates/prover/src/witness/components')])

# Test
os.chdir(os.path.join(clone_dir, 'stwo_cairo_prover'))
cargo_test_return_code = run_cmd(['cargo', 'test'], check_success=False)

if cargo_test_return_code != 0:
    print(f"Failure. cargo exited with {cargo_test_return_code}")
    exit(1)
else:
    print("Success!")
    exit(0)
