#!/usr/bin/python3

"""
A test to check that the autogenerated code compiles inside stwo-cairo. Should catch
mistakes such as missing imports in the autogenerated code.

The revision of stwo-cairo where the autogenerated code is supposed to compile is
taken from the file `supported-stwo-cairo-rev` file.
"""

import subprocess
import re
import os

try:
    import tomllib
except ModuleNotFoundError:
    # tomllib only exists in Python >= 3.11. If not found - use the bundled copy
    import tomllib_py3_11 as tomllib

def run_cmd(args, check_success=True):
    print(f"Running {args}")
    return_code = subprocess.call(args)
    if check_success:
        assert return_code == 0, f"Command exited with {return_code}"
    return return_code

def get_stwo_cairo_commit():
    result = None
    cargo_lock = tomllib.load(open(os.path.join(repository_root, "Cargo.lock"), "rb"))
    for pkg in cargo_lock['package']:
        if pkg['name'] != 'stwo-cairo-common':
            continue
        assert result is None, "Cannot get stwo-cairo revision: Multiple stwo-cairo entries in Cargo.lock"

        match = re.match('git\\+https://github\\.com/starkware-libs/stwo-cairo\\.git\\?rev=[0-9a-f]+#([0-9a-f]{40})$', pkg['source'])
        assert match is not None, f"Cannot get stwo-cairo revision: unsupported source '{pkg['source']}'"

        result = match.group(1)
    return result


script_dir = os.path.abspath(os.path.dirname(__file__))
repository_root = os.path.join(script_dir, "..")
clone_dir = os.path.join(repository_root, "build", "stwo-cairo")


stwo_cairo_commit = get_stwo_cairo_commit()
print(f"Testing against stwo commit {stwo_cairo_commit}")

if not os.path.exists(clone_dir):
    # Clone stwo-cairo
    run_cmd(['git', 'clone', '--depth=1', 'https://github.com/starkware-libs/stwo-cairo', clone_dir])
else:
    # Use the existing stwo-cairo clone
    run_cmd(['git', '-C', clone_dir, 'reset', '--hard'])

# Checkout the required revision
run_cmd(['git', '-C', clone_dir, 'fetch', '--depth=1', 'origin', stwo_cairo_commit])
run_cmd(['git', '-C', clone_dir, 'checkout', stwo_cairo_commit])

# Generate code
run_cmd(['cargo', 'run', '--bin', 'cairo_code_gen', '--',
         '--source', os.path.join(repository_root, 'crates/compiled_casm_air/src/compiled_jsons'),
         '--rust-constraints-dest', os.path.join(clone_dir, 'stwo_cairo_prover/crates/cairo-air/src/components'),
         '--cairo-constraints-dest', os.path.join(clone_dir, 'stwo_cairo_verifier/crates/cairo_air/src/components'),
         '--witness-dest', os.path.join(clone_dir, 'stwo_cairo_prover/crates/prover/src/witness/components')])

# Test Rust generated code
# We only run the tests for the stwo_cairo_prover and cairo-air packages as these are the only ones
# that depend on the generated code.
os.chdir(os.path.join(clone_dir, 'stwo_cairo_prover'))
cargo_test_return_code = run_cmd(['cargo', 'test', '--package', 'stwo_cairo_prover'], check_success=False)
if cargo_test_return_code != 0:
    print(f"Failure: cargo test in stwo_cairo_prover exited with {cargo_test_return_code}")
    exit(1)

cargo_test_return_code = run_cmd(['cargo', 'test', '--package', 'cairo-air'], check_success=False)
if cargo_test_return_code != 0:
    print(f"Failure: cargo test in cairo-air exited with {cargo_test_return_code}")
    exit(1)

# Test Cairo generated code
os.chdir(os.path.join(clone_dir, 'stwo_cairo_verifier'))
scarb_test_return_code = run_cmd(['scarb', 'test', '--package', 'stwo_cairo_air', '--features', 'qm31_opcode'], check_success=False)
if scarb_test_return_code != 0:
    print(f"Failure: scarb test exited with {scarb_test_return_code}")
    exit(1)

print("Success!")
exit(0)
