use air_compile::compiled_structs::CompiledAirFn;
use genco::lang::rust;
use genco::quote;
use indexmap::IndexMap;
use itertools::Itertools;

use crate::utils::{AUTOGENERATED_CODE_COMMENT, is_const_size_component};

pub fn generate_claims_cairo_file(
    compiled_registry: &IndexMap<String, CompiledAirFn>,
) -> rust::Tokens {
    let components_names = compiled_registry.keys().collect_vec();

    quote! {
        $(AUTOGENERATED_CODE_COMMENT.to_string())
        use stwo_constraint_framework::claim::ClaimTrait;
        use stwo_cairo_air::{PublicData, RelationUsesDict};
        use stwo_verifier_core::TreeArray;
        use stwo_verifier_core::channel::Channel;
        use stwo_verifier_core::utils::OptionImpl;
        $(&components_names.iter().map(|name| {
            format!("use crate::components::{name};")
        }).collect_vec().join("\n"))
        use crate::components;
        use super::claim::{FlatClaim, FlatClaimTrait};
        use crate::cairo_air::override_preprocessed_trace_log_sizes;
        use stwo_constraint_framework::tree_array_concat_cols;
        use crate::components::memory_address_to_id::MEMORY_ADDRESS_TO_ID_SPLIT;


        #[derive(Drop, Serde)]
        pub struct CairoClaim {
            pub public_data: PublicData,
            $(&components_names.iter().map(|name| {
                format!("pub {name}: Option<components::{name}::Claim>")
            }).collect_vec().join(", "))
        }

        $(generate_cairo_claim_impl(compiled_registry))
    }
}

fn generate_cairo_claim_impl(compiled_registry: &IndexMap<String, CompiledAirFn>) -> rust::Tokens {
    let mut accumulate_body = rust::Tokens::new();
    let mut log_sizes_body = rust::Tokens::new();
    let mut flatten_claim_body = rust::Tokens::new();

    for (name, compiled_air_fn) in compiled_registry {
        // Add to accumulate_relation_uses() body.
        if !is_const_size_component(compiled_air_fn) {
            accumulate_body.append(quote! {
                if let Some(claim) = self.$(name) {
                    claim.accumulate_relation_uses(ref relation_uses);
                }
            });
        }

        // Add to log_sizes() body.
        log_sizes_body.append(quote! {
            if let Some(claim) = self.$(name) {
                log_sizes_list.append(claim.log_sizes());
            }
        });

        // Add to flatten_claim() body.
        if name == "memory_id_to_big" {
            flatten_claim_body.append(quote! {
                let memory_id_to_big::Claim {
                    big_log_sizes,
                } = self.memory_id_to_big.as_snap().unwrap();
                assert!(big_log_sizes.len() <= MEMORY_ADDRESS_TO_ID_SPLIT);
                for log_size in big_log_sizes {
                    component_log_sizes.append(*log_size);
                    component_enable_bits.append(true);
                }
                for _ in 0..(MEMORY_ADDRESS_TO_ID_SPLIT - big_log_sizes.len()) {
                    component_enable_bits.append(false);
                }
            });
        } else {
            let (claim_binding, log_size_expr) = if is_const_size_component(compiled_air_fn) {
                (quote! { _c }, quote! { $(name)::LOG_SIZE })
            } else {
                (quote! { c }, quote! { *c.log_size })
            };
            flatten_claim_body.append(quote! {
                if let Some($(claim_binding)) = self.$(name) {
                    component_log_sizes.append($(log_size_expr));
                    component_enable_bits.append(true);
                } else {
                    component_enable_bits.append(false);
                }
            });
        }
    }

    quote! {
        pub impl CairoClaimImpl of ClaimTrait<CairoClaim> {
            fn log_sizes(self: @CairoClaim) -> TreeArray<Span<u32>> {
                let mut log_sizes_list = array![];
                $(log_sizes_body)
                let aggregated_log_sizes = tree_array_concat_cols(log_sizes_list);
                override_preprocessed_trace_log_sizes(aggregated_log_sizes)
            }

            fn mix_into(self: @CairoClaim, ref channel: Channel) {
                let flat_claim = self.flatten_claim();
                flat_claim.mix_into(ref channel);
            }

            fn accumulate_relation_uses(self: @CairoClaim, ref relation_uses: RelationUsesDict) {
                $(accumulate_body)
            }
        }

        #[generate_trait]
        pub impl CairoClaimFlattenImpl of CairoClaimFlattenTrait {
            $("/// Create flat claim out of the given claim.")
            fn flatten_claim(self: @CairoClaim) -> FlatClaim {
                let mut component_enable_bits = array![];
                let mut component_log_sizes = array![];

                $(flatten_claim_body)

                FlatClaim {
                    component_enable_bits: component_enable_bits.span(),
                    component_log_sizes: component_log_sizes.span(),
                    public_data: self.public_data.clone(),
                }
            }
        }
    }
}
