[package]
name = "air_code_gen"
version.workspace = true
edition.workspace = true

[dependencies]
compiled_casm_air = { path = "../compiled_casm_air" }
genco.workspace = true
itertools.workspace = true
xshell.workspace = true
tempfile = "3.10.1"
pretty_assertions = "1.4.0"
[features]
default = []
fix_code = []

[dev-dependencies]
rand = { version = "0.8.5" }
serde_json.workspace = true
