name: CI

on:
  push:
    branches:
      - main
      - main-v[0-9].**
    tags:
      - v[0-9].**

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - auto_merge_enabled

  merge_group:
    types:
      - checks_requested

env:
  STABLE_VERSION: "1.90.0"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: ${{ env.STABLE_VERSION }}
      - uses: Swatinem/rust-cache@v2
      - run: scripts/rust_fmt.sh --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: ${{ env.STABLE_VERSION }}
      - uses: Swatinem/rust-cache@v2
      - run: scripts/clippy.sh

  js-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.10
      - run: scripts/js_typecheck.sh

  test-generated-code-in-stwo-cairo:
    runs-on: ubuntu-latest-l
    steps:
      - uses: actions/checkout@v2
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.12.2"
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: nightly-2025-06-23
      - uses: Swatinem/rust-cache@v2
      - run: scripts/test_generated_code_stwo_cairo.py

  test-generated-code-in-stwo-circuits:
    runs-on: ubuntu-latest-l
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: nightly-2025-06-23
      - uses: Swatinem/rust-cache@v2
      - run: scripts/test_generated_code_stwo_circuits.py

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.12.2"
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          profile: minimal
          toolchain: ${{ env.STABLE_VERSION }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --release

  machete-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Machete
        uses: bnjbvr/cargo-machete@main

  all-tests:
    if: always()
    runs-on: ubuntu-latest
    needs:
    - clippy
    - format
    - run-tests
    - machete-check
    - test-generated-code-in-stwo-cairo
    - test-generated-code-in-stwo-circuits
    steps:
    - name: Decide whether all the needed jobs succeeded or failed
      uses: re-actors/alls-green@v1.2.2
      with:
        jobs: ${{ toJSON(needs) }}
